create table if not exists public.editais (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references auth.users(id) on delete cascade,
  arquivo_nome text not null,
  arquivo_path text not null unique,
  tamanho_bytes bigint not null,
  status text not null default 'aguardando_ia' check (status in ('aguardando_ia','processando','concluido','erro')),
  concurso text,
  cargo text,
  banca text,
  data_prova date,
  resumo text,
  erro_processamento text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.edital_materias (
  id bigint generated by default as identity primary key,
  edital_id uuid not null references public.editais(id) on delete cascade,
  materia text not null,
  conteudo_programatico text[] not null default '{}',
  peso numeric(5,2),
  ordem integer not null default 0
);

alter table public.editais enable row level security;
alter table public.edital_materias enable row level security;

create policy "Aluno gerencia os próprios editais" on public.editais for all to authenticated using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);
create policy "Aluno visualiza matérias dos próprios editais" on public.edital_materias for select to authenticated using (exists (select 1 from public.editais e where e.id = edital_id and e.usuario_id = auth.uid()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('editais', 'editais', false, 26214400, array['application/pdf'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "Aluno envia os próprios editais" on storage.objects for insert to authenticated with check (bucket_id = 'editais' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Aluno acessa os próprios editais" on storage.objects for select to authenticated using (bucket_id = 'editais' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Aluno exclui os próprios editais" on storage.objects for delete to authenticated using (bucket_id = 'editais' and (storage.foldername(name))[1] = auth.uid()::text);
