-- Mapa de classificacao semantica das questoes validas de Tempos e modos verbais
-- (curso_conteudos.id = 31, assunto_id = 54,
-- materia_id = 6), gerado pelo pipeline automatico
-- (scripts/curadoria-pedagogica/gerar-mapa.mjs) a partir de
-- config/tempos_e_modos_verbais.mapa.json — produto de leitura humana do enunciado + TODAS
-- as alternativas de cada questao (nunca por ID, banca, concurso ou
-- palavra-chave isolada). Mesmo metodo de
-- supabase/mapa_classificacao_improbidade.sql.
--
-- SOMENTE LEITURA. Este arquivo nao escreve nada — e a fonte unica de
-- verdade (mapa aprovado) que
--   classificar_questoes_unidades_tempos_e_modos_verbais_teste_rollback.sql
--   classificar_questoes_unidades_tempos_e_modos_verbais.sql
-- devem replicar byte a byte na tabela temporaria _mapa antes de aplicar.
--
-- Unidades oficiais do conteudo 31 (apos curadoria_unidades_tempos_e_modos_verbais.sql):
--   U1 d54fb675-78a8-4efb-a99a-44359555d28f  ordem 1  Tempos e modos verbais
--
-- Resultado da curadoria: 11/13 questoes ativas
-- classificadas, multiunidade: nenhuma, excluidas: 693 (FORA_DE_ESCOPO_MORFOLOGIA_LOCUCAO_VERBAL — cobra identificacao da categoria morfologica 'locucao verbal' ('estavam relacionados') em contraste com locucao adverbial, locucao adjetiva, substantivo composto e adjetivo composto; nenhuma alternativa envolve tempo ou modo verbal, o tempo do auxiliar 'estavam' (preterito imperfeito) e incidental, nao e o que se pergunta. Provavel destino futuro: Classes de palavras (conteudo 22, ja concluido) ou conteudo de estrutura/formacao de palavras da fila, a confirmar. Nao realocada nesta etapa.); 893 (QUESTAO_HIBRIDA_MULTICONTEUDO — cobra 4 assertivas de habilidades distintas sobre a palavra 'Trabalhando': (I) gerundio nao e preterito [tempos/modos verbais], (II) ausencia de prefixo [formacao de palavras, fora de escopo], (III) presenca de digrafos lh+an [fonemas e digrafos, conteudo 34 ja concluido], (IV) gerundio e forma nominal [tempos/modos verbais]. Para resolver integralmente a questao o aluno nao pode depender apenas da aula de tempos e modos verbais — por isso NAO e vinculada como pratica especifica desta unidade. O fenomeno 'gerundio como forma nominal' cobrado pelos itens I e IV permanece registrado no escopo pedagogico e no raio-x de incidencia como evidencia real de que a Fundatec cobrou esse conceito (Profis Pref Viamao/2022), distinguindo 'evidencia de que caiu' de 'questao adequada para pratica especifica da unidade'. Pode ser reaproveitada futuramente em revisao integrada, simulado ou missao final. Nao realocada nesta etapa.).

-- ============================================================================
-- 1) MAPA — uma linha por vinculo (questao multiunidade = mais de uma linha).
-- ============================================================================
with mapa (questao_id, unidade_pedagogica_id, ordem_unidade, tema, justificativa, confianca) as (
  values
    (240, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Pretérito imperfeito do subjuntivo — desinência -sse (origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO (banca=''Papiro'', concurso=''PAPIRO - Estilo Fundatec - BM RS'', 2026) — material suplementar de prática, NÃO conta como incidência histórica real da Fundatec no raio-x pré-edital. Regra testada: em ''Se eu estudasse mais, teria melhor desempenho'', ''estudasse'' está no pretérito imperfeito do subjuntivo, reconhecido pela desinência ''-sse-''. Categoria: A) regra produtiva.', 'alta'),
    (241, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Futuro do subjuntivo × infinitivo pessoal (origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO — material suplementar de prática, NÃO conta como incidência histórica real. Regra testada: em ''Quando eu chegar, avisarei'', ''chegar'' está no futuro do subjuntivo. CORREÇÃO APLICADA: a distinção com o infinitivo pessoal (formas coincidentes em verbos regulares) deve ser ensinada como teste contextual — ''quando''/''se'' com valor de eventualidade futura é pista forte de futuro do subjuntivo, preposição introduzindo oração reduzida é pista de infinitivo — dependendo da estrutura sintática e da função da oração, nunca como regra universal infalível. Categoria: D) contraste.', 'alta'),
    (242, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Futuro do pretérito do indicativo — desinência -ria (origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO — material suplementar de prática, NÃO conta como incidência histórica real. Regra testada: ''faria'' está no futuro do pretérito do indicativo, reconhecido pela desinência ''-ria-''. Categoria: A) regra produtiva.', 'alta'),
    (692, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Correlação condicional: se+pretérito imperfeito do subjuntivo ↔ futuro do pretérito do indicativo', 'Questão real (Fundatec, Esc Pol PC-RS/2026). Regra testada: ''justificaria'' está no futuro do pretérito do indicativo, em correlação condicional com ''se isso viesse'' (pretérito imperfeito do subjuntivo), expressando ação hipotética. NÚCLEO IMPORTANTE confirmado por prova real recente — ensinar forma → relação temporal → valor hipotético/condicional, não apenas a desinência mecanicamente. Categoria: A) regra produtiva.', 'alta'),
    (763, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Futuro do presente do indicativo — reescrita a partir de forma composta', 'Questão real (Fundatec, Tec Per IGP RS/Técnico em Química/2025). Regra testada: ''têm'' (3ª pl.), reescrito no futuro do presente do indicativo, torna-se ''terão''. CORREÇÃO APLICADA: a fórmula ''infinitivo + -ão'' é regra de bolso válida para verbos regulares, mas tem limite explícito em verbos com radical futuro irregular (fazer→farão, dizer→dirão, trazer→trarão) — ensinar regra de bolso + limite da regra de bolso. Categoria: A) regra produtiva.', 'alta'),
    (764, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Valores semânticos dos modos verbais em texto real (indicativo × subjuntivo)', 'Questão real (Fundatec, Del Pol PC-RS/2025). Regra testada: ''saibam'' (presente do subjuntivo) exprime conjectura incerta mas possível, em contraste com formas do indicativo do mesmo texto. CORREÇÃO APLICADA: não ensinar como definição absoluta (''indicativo=certeza, subjuntivo=incerteza, imperativo=ordem'') — apresentar como primeiro mapa mental útil, mas com nuance: indicativo tende a apresentar o conteúdo como fato/ocorrência/constatação assumida pelo enunciador; subjuntivo aparece frequentemente em hipótese/possibilidade/desejo/dúvida/condição/eventualidade/avaliação/não asserção; imperativo pode expressar ordem/pedido/conselho/convite/orientação/instrução — a questão real determina qual valor está sendo explorado no contexto. Categoria: E) habilidade semântica/interpretativa.', 'alta'),
    (765, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Pretérito perfeito do indicativo — verbo regular (perceber) × irregular (estar)', 'Questão real (Fundatec, Del Pol PC-RS/2025). Regra testada: ''percebem'' e ''estão'', reescritos no pretérito perfeito do indicativo (3ª pl.), tornam-se ''perceberam'' (regular) e ''estiveram'' (irregular). Categoria: A) regra produtiva + B) regra morfológica (irregularidade verbal).', 'alta'),
    (766, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Futuro do presente do indicativo do verbo ''vir'' + concordância nominal do particípio', 'Questão real (Fundatec, Del Pol PC-RS/2025). Regra testada: ''o controle vem'' reescrito no plural e no futuro do presente torna-se ''os controles virão disfarçados'' (vir, 3ª pl. futuro do presente, com concordância do particípio adjetivado). Distratores exploram a confusão clássica VIR × VER na 3ª pessoa do plural (veem/vieram/viram/vêm × virão). Categoria: A) regra produtiva + D) contraste.', 'alta'),
    (767, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Futuro do pretérito do indicativo × inexistência de ''futuro do pretérito do subjuntivo''', 'Questão real (Fundatec, GCM Sant''Ana do Livramento/2025). Regra testada: ''fracassaria'' está no modo indicativo, futuro do pretérito. CONFIRMADO: o modo subjuntivo possui apenas os tempos simples presente, pretérito imperfeito e futuro — ''futuro do pretérito do subjuntivo'' NÃO EXISTE, sendo pegadinha típica de banca (nomes plausíveis de tempos inexistentes). Categoria: D) contraste.', 'alta'),
    (811, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Futuro do presente do indicativo — reescrita a partir do pretérito imperfeito', 'Questão real (Fundatec, GM Pref Imbé/2023). Regra testada: ''castigavam'' (pretérito imperfeito), reescrito no futuro do presente do indicativo (3ª pl.), torna-se ''castigarão''. Mesma regra de bolso e limite de Q763 (verbos regulares × radicais futuros irregulares). Categoria: A) regra produtiva.', 'alta'),
    (894, 'd54fb675-78a8-4efb-a99a-44359555d28f'::uuid, 1, 'Presente do subjuntivo → pretérito imperfeito do subjuntivo (mesma flexão modal)', 'Questão real (Fundatec, TA Pol Pen PP-RS/2022). Regra testada: ''estejamos'' está no presente do subjuntivo; flexionado no pretérito imperfeito do mesmo modo, torna-se ''estivéssemos''. Reaproveita o artigo ''RS Seguro'' já usado em Ortografia/Acentuação/Fonemas (conteúdos 20/26/34, já concluídos), aqui testando um par de tempos do subjuntivo. Categoria: A) regra produtiva.', 'alta')
)
select * from mapa order by questao_id, ordem_unidade;

-- ============================================================================
-- 2) LISTAS EXPLICITAS.
-- ============================================================================

-- 2a) Questoes classificadas (11/13).
-- 240,241,242,692,763,764,765,766,767,811,894

-- 2b) Questoes multiunidade: nenhuma

-- 2c) Questoes excluidas intencionalmente (fora de escopo/pendente de saneamento): 693 (FORA_DE_ESCOPO_MORFOLOGIA_LOCUCAO_VERBAL — cobra identificacao da categoria morfologica 'locucao verbal' ('estavam relacionados') em contraste com locucao adverbial, locucao adjetiva, substantivo composto e adjetivo composto; nenhuma alternativa envolve tempo ou modo verbal, o tempo do auxiliar 'estavam' (preterito imperfeito) e incidental, nao e o que se pergunta. Provavel destino futuro: Classes de palavras (conteudo 22, ja concluido) ou conteudo de estrutura/formacao de palavras da fila, a confirmar. Nao realocada nesta etapa.); 893 (QUESTAO_HIBRIDA_MULTICONTEUDO — cobra 4 assertivas de habilidades distintas sobre a palavra 'Trabalhando': (I) gerundio nao e preterito [tempos/modos verbais], (II) ausencia de prefixo [formacao de palavras, fora de escopo], (III) presenca de digrafos lh+an [fonemas e digrafos, conteudo 34 ja concluido], (IV) gerundio e forma nominal [tempos/modos verbais]. Para resolver integralmente a questao o aluno nao pode depender apenas da aula de tempos e modos verbais — por isso NAO e vinculada como pratica especifica desta unidade. O fenomeno 'gerundio como forma nominal' cobrado pelos itens I e IV permanece registrado no escopo pedagogico e no raio-x de incidencia como evidencia real de que a Fundatec cobrou esse conceito (Profis Pref Viamao/2022), distinguindo 'evidencia de que caiu' de 'questao adequada para pratica especifica da unidade'. Pode ser reaproveitada futuramente em revisao integrada, simulado ou missao final. Nao realocada nesta etapa.)

-- ============================================================================
-- 3) Cobertura por unidade (questoes distintas). NAO forca nenhuma unidade
--    a atingir 10; unidades fracas sao GAP REAL DO BANCO, nao erro tecnico.
-- ============================================================================
-- U1 Tempos e modos verbais: 11 questoes distintas
-- Total de vinculos esperados: 11 (11 questoes distintas
-- + 0 vinculo(s) extra(s) de multiunidade).
