-- Mapa de classificacao semantica das questoes validas de Internet e navegadores
-- (curso_conteudos.id = 38, assunto_id = 62,
-- materia_id = 9), gerado pelo pipeline automatico
-- (scripts/curadoria-pedagogica/gerar-mapa.mjs) a partir de
-- config/internet_e_navegadores.mapa.json — produto de leitura humana do enunciado + TODAS
-- as alternativas de cada questao (nunca por ID, banca, concurso ou
-- palavra-chave isolada). Mesmo metodo de
-- supabase/mapa_classificacao_improbidade.sql.
--
-- SOMENTE LEITURA. Este arquivo nao escreve nada — e a fonte unica de
-- verdade (mapa aprovado) que
--   classificar_questoes_unidades_internet_e_navegadores_teste_rollback.sql
--   classificar_questoes_unidades_internet_e_navegadores.sql
-- devem replicar byte a byte na tabela temporaria _mapa antes de aplicar.
--
-- Unidades oficiais do conteudo 38 (apos curadoria_unidades_internet_e_navegadores.sql):
--   U1 b66e09ca-3dc1-4b63-879d-c81292b94550  ordem 1  Navegadores e ferramentas web
--   U2 d9153747-6150-4a1f-8bb8-f4ea433f672f  ordem 2  Internet: conceitos, arquitetura e protocolos
--
-- Resultado da curadoria: 18/21 questoes ativas
-- classificadas, multiunidade: nenhuma, excluidas: 64 (PENDENCIA_DE_FIDELIDADE_VISUAL_Q64 — enunciado descreve verbalmente um ícone do Google Drive ('silhueta de pessoa com sinal de adição') com estrutura sintática idêntica à de Q497 (confirmada como dependente de imagem original). Prova original (BM RS Soldado de Primeira Classe 2025, Questão 50) NÃO localizada apesar de múltiplas tentativas de busca. Fidelidade ainda não demonstrada (nem confirmada nem refutada) — critério conservador aplicado: não vincular enquanto a dúvida material persistir. Não declarado definitivamente como problema de fidelidade confirmado; não é regra de taxonomia. Ativa, intacta, sem alteração de conteúdo.); 496 (PENDENCIA_DE_FIDELIDADE_VISUAL_Q496 — mesma estrutura suspeita de Q64/Q497 ('o botão representado por uma caixa com uma seta apontando para cima e para fora tem como função:'). Prova original (Tec Pref Viamão Agrícola 2022) NÃO localizada. Fidelidade ainda não demonstrada. Ativa, intacta, sem alteração de conteúdo.); 497 (PROBLEMA_DE_FIDELIDADE_IMAGEM_Q497 — CONFIRMADO via prova original localizada e extraída (TA Pol Pen/PP RS/2022, Questão 28): 'A Figura 3 abaixo apresenta a janela principal do navegador Mozilla Firefox... Qual a função do ícone indicado pela seta nº 1 da Figura acima?'. O Papiro substituiu a imagem original (Figura 3 com seta indicadora) por descrição textual do próprio ícone diretamente no enunciado ('uma seta circular'), entregando ao aluno a informação que o candidato original tinha que reconhecer visualmente. A habilidade original (reconhecimento visual de ícone em screenshot) e a habilidade Papiro (leitura de descrição textual) não são equivalentes — mudança material confirmada. Ativa, intacta, sem alteração de conteúdo.).

-- ============================================================================
-- 1) MAPA — uma linha por vinculo (questao multiunidade = mais de uma linha).
-- ============================================================================
with mapa (questao_id, unidade_pedagogica_id, ordem_unidade, tema, justificativa, confianca) as (
  values
    (63, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Permissões de moderador em videochamada (Google Meet)', 'ORIGEM: REAL (Fundatec, Brigada Militar RS - Soldado de Primeira Classe, 2025). Fenômeno testado: no Google Meet, o moderador/anfitrião pode desativar câmera/microfone de participantes, moderar chat e criar enquetes, mas NUNCA pode ativar remotamente câmera/microfone de terceiros sem autorização expressa (apenas solicitar). Categoria: B) regra factual de produto.', 'alta'),
    (94, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Navegação anônima (Google Chrome)', 'ORIGEM: REAL (Fundatec, SUSEPE RS - Agente Penitenciário, 2022). Fenômeno testado: a janela anônima do Chrome não salva localmente histórico/cookies/dados de formulário após o fechamento, mas downloads e favoritos criados permanecem salvos, e a atividade continua visível para provedores de internet e administradores de rede. Categoria: B) regra factual de produto.', 'alta'),
    (98, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Limpar dados de navegação (Google Chrome)', 'ORIGEM: REAL (Fundatec, SUSEPE RS - Agente Penitenciário Administrativo, 2022). Fenômeno testado: o recurso local ''Limpar dados de navegação'' do Chrome apaga histórico de navegação/download, cookies, cache e senhas salvas; o ''Histórico de pesquisa'' é gerenciado nos servidores da conta Google (''Minha Atividade''), não sendo item direto da ferramenta de cache local. Categoria: B) regra factual de produto.', 'alta'),
    (106, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Operador de busca por frase exata (Google Drive)', 'ORIGEM: REAL (Fundatec, Brigada Militar RS - Soldado Nível III, 2022). Fenômeno testado: no ''Pesquisar no Drive'', o operador de aspas duplas busca a correspondência exata de uma frase; distratores cobrem outros símbolos (+, %, -) com funções diferentes ou inexistentes nesse buscador. Categoria: B) regra factual de produto.', 'alta'),
    (107, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Firefox Screenshots — formas de acionamento', 'ORIGEM: REAL (Fundatec, Brigada Militar RS - Soldado Nível III, 2022). Fenômeno testado: o recurso Firefox Screenshots pode ser acionado pelo menu de contexto (botão direito) ou pelo atalho Ctrl+Shift+S; F5 é atalho de recarregar página, sem relação com captura de tela. Categoria: B) regra factual de produto.', 'média'),
    (630, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Camadas da internet — Surface Web', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: Surface Web é a camada aberta e indexada pelos motores de busca tradicionais, distinta de Deep Web (não indexada), Dark Web (subcamada restrita da Deep Web), Extranet e Darknet. Categoria: A) regra conceitual.', 'alta'),
    (631, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Fingerprinting como técnica de rastreamento web', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: fingerprinting identifica unicamente um dispositivo/navegador combinando características técnicas (SO, resolução, fontes, fuso horário), sem depender de cookies armazenados ou login — distinto de cookies, rastreamento por URL, ID de usuário autenticado e pixels de rastreamento. DECISÃO DE FRONTEIRA CONFIRMADA: habilidade nuclear é reconhecimento de mecanismo técnico de rastreamento web (nenhuma alternativa trata de ameaça/contramedida/controle de segurança/risco/ataque/proteção) — permanece em Internet e navegadores, não em Segurança da informação (conteúdo ainda não mapeado nesta fila); associação temática com privacidade não equivale a habilidade nuclear de segurança. Categoria: A) regra conceitual.', 'alta'),
    (632, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'DNS × DHCP', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: DNS traduz nomes de domínio em endereços IP e opera na camada de APLICAÇÃO do modelo TCP/IP (porta 53), não na camada de transporte; a configuração automática de parâmetros de rede (IP, máscara, gateway) é função do DHCP, não do DNS. Categoria: D) contraste técnico entre protocolos concorrentes.', 'alta'),
    (633, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Computação em nuvem — modelos de serviço e nuvem pública', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: nuvens públicas pertencem a provedores terceirizados; o modelo de nuvem substitui alto investimento inicial (CapEx) por consumo sob demanda (OpEx); IaaS é o modelo mais BÁSICO (infraestrutura), não o mais completo — SaaS é o mais abrangente para o usuário final. CAUTELA: apresentar IaaS/PaaS/SaaS em termos de camada de serviço e responsabilidade gerenciada pelo provedor (quanto mais se caminha de IaaS a SaaS, mais componentes ficam a cargo do provedor), não como ranking absoluto de qualidade. Categoria: D) contraste entre modelos de serviço.', 'alta'),
    (634, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Reuniões instantâneas e múltiplos dispositivos (Microsoft Teams)', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: no Teams é possível iniciar reunião instantânea (''Reunir agora'') a partir de qualquer chat/canal sem agendamento prévio; também é possível ingressar com dois dispositivos na mesma conta e convidar novos participantes durante a reunião em andamento. Categoria: B) regra factual de produto.', 'alta'),
    (636, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Abas contêiner e fixar aba (Mozilla Firefox)', 'ORIGEM: REAL (Fundatec, GM (Pref Gravataí)/Pref Gravataí, 2026). Fenômeno testado: ''Abas contêiner'' isola identidades de navegação (cookies/sessões) por contexto de cor; ''Fixar aba'' mantém uma página sempre acessível como ícone compacto na barra de abas. Categoria: B) regra factual de produto.', 'alta'),
    (702, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Estrutura de endereçamento IPv4', 'ORIGEM: REAL (Fundatec, Per Crim (IGP RS)/IGP RS/Contabilidade e Economia, 2025). Fenômeno testado: um endereço IPv4 válido é formado por exatamente 4 octetos decimais (0-255) separados por pontos; distratores apresentam 1, 2, 3 ou 5 blocos numéricos. Categoria: A) regra conceitual.', 'alta'),
    (703, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Computação em nuvem — definição geral e responsabilidade compartilhada', 'ORIGEM: REAL (Fundatec, Per Crim (IGP RS)/IGP RS/Contabilidade e Economia, 2025). Fenômeno testado: cloud computing provê acesso remoto sob demanda a um pool compartilhado de recursos configuráveis (caracterização próxima à do NIST); opera sob modelo de responsabilidade compartilhada (segurança DA nuvem é do provedor, segurança DENTRO da nuvem é do cliente); depende de conectividade de rede; grandes provedores oferecem plataformas de IA e usam criptografia/certificações de segurança. Categoria: A) regra conceitual.', 'alta'),
    (704, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Conceito de URL', 'ORIGEM: REAL (Fundatec, Tec Per (IGP RS)/IGP RS/Técnico em Química, 2025). Fenômeno testado: URL é a cadeia de caracteres padronizada que especifica o endereço único de um recurso na web (protocolo + domínio + caminho), distinta de HTTP (protocolo), Storage, VPN e WWW. Categoria: A) regra conceitual.', 'alta'),
    (705, 'd9153747-6150-4a1f-8bb8-f4ea433f672f'::uuid, 2, 'Deep Web × Dark Web — acesso e ferramentas', 'ORIGEM: REAL (Fundatec, Del Pol (PC RS)/PC RS, 2025). Fenômeno testado: Deep Web e Dark Web não são indexadas por buscadores, mas a Deep Web é acessível por navegadores comuns mediante login (sistemas bancários, e-mails, intranets); a Dark Web exige softwares/redes específicas como o Tor Browser — o ''Autopsy'' citado no distrator é ferramenta de análise forense digital, não navegador de acesso à Dark Web. CUIDADO: não equiparar Deep Web a conteúdo ilegal nem a Dark Web. Categoria: D) contraste técnico (mesmo subassunto de Q630, fato distinto testado).', 'alta'),
    (770, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Painel Lateral (Google Chrome)', 'ORIGEM: REAL (Fundatec, GM (Pref Foz do Iguaçu)/Pref Foz do Iguaçu, 2024). Fenômeno testado: o Painel Lateral do Chrome reúne Lista de leitura, Histórico e Favoritos — as três assertivas do enunciado estão corretas. Categoria: B) regra factual de produto.', 'alta'),
    (792, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Recursos comuns entre Chrome e Firefox (comparação)', 'ORIGEM: REAL (Fundatec, GM (Pref Imbé)/Pref Imbé, 2023). Fenômeno testado: favoritos, navegação privativa (Firefox), atalhos de site (Chrome) e múltiplas abas simultâneas são recursos presentes em ambos os navegadores — todas as 4 assertivas corretas. Categoria: B) regra factual de produto (contraste entre navegadores).', 'alta'),
    (833, 'b66e09ca-3dc1-4b63-879d-c81292b94550'::uuid, 1, 'Extensões, Firefox Sync e barra de endereços inteligente (Mozilla Firefox)', 'ORIGEM: REAL (Fundatec, Tec (Pref Viamão)/Pref Viamão/Agrícola, 2022). Fenômeno testado: o Firefox permite instalar extensões livremente (assertiva I é falsa ao negar isso); Firefox Sync sincroniza favoritos/senhas/histórico/extensões entre dispositivos; a Awesome Bar sugere termos com base em histórico, marcadores e buscas populares. Categoria: B) regra factual de produto.', 'alta')
)
select * from mapa order by questao_id, ordem_unidade;

-- ============================================================================
-- 2) LISTAS EXPLICITAS.
-- ============================================================================

-- 2a) Questoes classificadas (18/21).
-- 63,94,98,106,107,630,631,632,633,634,636,702,703,704,705,770,792,833

-- 2b) Questoes multiunidade: nenhuma

-- 2c) Questoes excluidas intencionalmente (fora de escopo/pendente de saneamento): 64 (PENDENCIA_DE_FIDELIDADE_VISUAL_Q64 — enunciado descreve verbalmente um ícone do Google Drive ('silhueta de pessoa com sinal de adição') com estrutura sintática idêntica à de Q497 (confirmada como dependente de imagem original). Prova original (BM RS Soldado de Primeira Classe 2025, Questão 50) NÃO localizada apesar de múltiplas tentativas de busca. Fidelidade ainda não demonstrada (nem confirmada nem refutada) — critério conservador aplicado: não vincular enquanto a dúvida material persistir. Não declarado definitivamente como problema de fidelidade confirmado; não é regra de taxonomia. Ativa, intacta, sem alteração de conteúdo.); 496 (PENDENCIA_DE_FIDELIDADE_VISUAL_Q496 — mesma estrutura suspeita de Q64/Q497 ('o botão representado por uma caixa com uma seta apontando para cima e para fora tem como função:'). Prova original (Tec Pref Viamão Agrícola 2022) NÃO localizada. Fidelidade ainda não demonstrada. Ativa, intacta, sem alteração de conteúdo.); 497 (PROBLEMA_DE_FIDELIDADE_IMAGEM_Q497 — CONFIRMADO via prova original localizada e extraída (TA Pol Pen/PP RS/2022, Questão 28): 'A Figura 3 abaixo apresenta a janela principal do navegador Mozilla Firefox... Qual a função do ícone indicado pela seta nº 1 da Figura acima?'. O Papiro substituiu a imagem original (Figura 3 com seta indicadora) por descrição textual do próprio ícone diretamente no enunciado ('uma seta circular'), entregando ao aluno a informação que o candidato original tinha que reconhecer visualmente. A habilidade original (reconhecimento visual de ícone em screenshot) e a habilidade Papiro (leitura de descrição textual) não são equivalentes — mudança material confirmada. Ativa, intacta, sem alteração de conteúdo.)

-- ============================================================================
-- 3) Cobertura por unidade (questoes distintas). NAO forca nenhuma unidade
--    a atingir 10; unidades fracas sao GAP REAL DO BANCO, nao erro tecnico.
-- ============================================================================
-- U1 Navegadores e ferramentas web: 10 questoes distintas
-- U2 Internet: conceitos, arquitetura e protocolos: 8 questoes distintas
-- Total de vinculos esperados: 18 (18 questoes distintas
-- + 0 vinculo(s) extra(s) de multiunidade).
