-- Mapa de classificacao semantica das questoes validas de Windows
-- (curso_conteudos.id = 35, assunto_id = 28,
-- materia_id = 9), gerado pelo pipeline automatico
-- (scripts/curadoria-pedagogica/gerar-mapa.mjs) a partir de
-- config/windows.mapa.json — produto de leitura humana do enunciado + TODAS
-- as alternativas de cada questao (nunca por ID, banca, concurso ou
-- palavra-chave isolada). Mesmo metodo de
-- supabase/mapa_classificacao_improbidade.sql.
--
-- SOMENTE LEITURA. Este arquivo nao escreve nada — e a fonte unica de
-- verdade (mapa aprovado) que
--   classificar_questoes_unidades_windows_teste_rollback.sql
--   classificar_questoes_unidades_windows.sql
-- devem replicar byte a byte na tabela temporaria _mapa antes de aplicar.
--
-- Unidades oficiais do conteudo 35 (apos curadoria_unidades_windows.sql):
--   U1 936d2d9d-0f83-4a25-8066-9e035a12ca16  ordem 1  Windows
--
-- Resultado da curadoria: 14/15 questoes ativas
-- classificadas, multiunidade: nenhuma, excluidas: 836 (DUPLICATA_Q836 — mesmo enunciado, mesmas 5 alternativas e mesmo gabarito (B) de Q101 ("praia ou serra?.pdf" como nome inválido pelo caractere '?'), mesmo bloco de Informática do concurso SUSEPE/Polícia Penal RS 01/2022 (cargos diferentes, mesma prova de origem). Q836 possui glitch textual "arquivoinválido" (sem espaço), enquanto Q101 é a versão mais limpa e foi escolhida como questão canônica vinculada. Q836 permanece ATIVA, INTACTA e SEM vínculo neste conteúdo — não corrigida, não desativada, não contabilizada como segunda incidência independente do fenômeno de caracteres proibidos.).

-- ============================================================================
-- 1) MAPA — uma linha por vinculo (questao multiunidade = mais de uma linha).
-- ============================================================================
with mapa (questao_id, unidade_pedagogica_id, ordem_unidade, tema, justificativa, confianca) as (
  values
    (31, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Lixeira (cobertura suplementar; origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO (banca="Papiro - estilo Fundatec", concurso="Brigada Militar do Rio Grande do Sul", ano=NULL) — PROBLEMA_DE_QUALIDADE_METADADOS_Q31 registrado (banca em formato não padronizado e ano ausente), sinalizado e NÃO corrigido nesta curadoria; o conteúdo é tecnicamente correto e a questão é vinculável como material suplementar de prática, sem contar para incidência histórica, recorrência, frequência Fundatec ou recência — registrada como COBERTURA_SUPLEMENTAR_WINDOWS. Fenômeno testado: mover um arquivo para a Lixeira permite restaurá-lo (gabarito A) — a Lixeira não criptografa (isso é BitLocker/EFS), não envia à nuvem (isso é OneDrive/Drive), não oculta arquivos (atributo de propriedades) e não afeta backups externos. Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (60, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Explorador de Arquivos — Barra de Acesso Rápido (origem=REAL)', 'ORIGEM: REAL (Fundatec, Brigada Militar RS - Soldado de Primeira Classe, 2025). FIDELIDADE: reavaliada nesta ordem (constava em lista de pendências históricas de suspeita visual) — a questão pede o nome de uma FUNÇÃO ausente da Barra de Acesso Rápido, sem depender de reconhecimento de ícone mostrado em imagem; concluído AUTOSSUFICIENTE_CONFIRMADA. Fenômeno testado: no Explorador de Arquivos do Windows 10, a Barra de Ferramentas de Acesso Rápido contém nativamente Nova Pasta, Desfazer, Refazer, Excluir e Propriedades — "Voltar" (gabarito E, EXCETO) é botão de navegação da barra de endereços, não da barra de acesso rápido. CAUTELA DE VERSÃO: fato historicamente cobrado nesta versão/época da prova (Windows 10, 2025), não necessariamente idêntico em toda interface futura. Categoria: B) regra factual de produto. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (101, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Caracteres proibidos em nomes de arquivo/pasta — questão canônica da duplicata Q101/Q836 (origem=REAL)', 'ORIGEM: REAL (Fundatec, SUSEPE RS - Agente Penitenciário, 2022). Questão canônica vinculada da duplicata Q101/Q836 (ver questoes_excluidas — Q836 é a mesma questão-fonte, com glitch textual, e permanece sem vínculo). Fenômeno testado: o caractere "?" é proibido em nomes de arquivo/pasta no Windows 10 — "praia ou serra?.pdf" é inválido (gabarito B), enquanto nomes com underline, acento, cerquilha, espaço, hífen, parênteses e números são válidos. RECORRÊNCIA: este fenômeno (caracteres proibidos) é RECORRENTE NESTE CORPUS, confirmado por uma segunda ocorrência independente em Q645 (prova distinta, caractere ":"). CAUTELA: ensinar apenas os 9 caracteres proibidos tradicionais (\ / : * ? " < > |) efetivamente comprovados por este banco, sem afirmar que são as únicas restrições possíveis para qualquer nome no Windows (existem também nomes reservados e restrições contextuais não cobradas aqui). Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (102, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Barra de Tarefas (origem=REAL)', 'ORIGEM: REAL (Fundatec, SUSEPE RS - Agente Penitenciário, 2022 — mesma prova de Q101). Fenômeno testado: julgamento de 3 assertivas sobre a Barra de Tarefas do Windows 10 — fixar aplicativo (verdadeiro) e verificar a hora do sistema (verdadeiro) são funções da Barra de Tarefas; esvaziar a Lixeira (falso) não é, pois a Lixeira fica na Área de Trabalho, sem atalho nativo na barra de tarefas para essa ação (gabarito D: I e III corretas). Distingue corretamente funções próprias da Barra de Tarefas de operações pertencentes a outros componentes do sistema (Lixeira). Categoria: A) regra conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (103, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Painel de Controle — categoria Programas (origem=REAL)', 'ORIGEM: REAL (Fundatec, SUSEPE RS - Agente Penitenciário Administrativo, 2022 — caderno de cargo distinto do mesmo concurso de Q101/Q102). Fenômeno testado: no Painel de Controle clássico do Windows 10 por categoria, a opção para desinstalar um programa está em "Programas" (gabarito A), distinta de Sistema e Segurança, Aparência e Personalização, Contas de Usuário e Rede e Internet. RECORRÊNCIA: Painel de Controle é fenômeno RECORRENTE NESTE CORPUS, confirmado por uma segunda ocorrência independente em Q711 (prova distinta, associação conceitual). CAUTELA DE VERSÃO: o Windows moderno também possui o aplicativo "Configurações" — esta questão permanece válida como evidência histórica da prova, mesmo com mudanças de interface entre versões. Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (108, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Modos de energia — Suspensão × Hibernação (origem=REAL)', 'ORIGEM: REAL (Fundatec, Brigada Militar RS - Soldado Nível III, 2022). Fenômeno testado: o estado de baixíssimo consumo de energia que mantém a sessão na memória RAM e permite retomada quase instantânea é a SUSPENSÃO (gabarito E), distinta de Hibernação (não citada como opção nesta questão, mas contrastada na justificativa pedagógica: retomada a partir de estado persistido em disco, não da RAM), Desconexão/logoff, Desligamento completo e Reinício. CAUTELA: usar o contraste Suspensão×Hibernação como explicação pedagógica tradicional, com limite — não reduzir a uma fórmula simplista "RAM vs disco" como se isso descrevesse de forma completa toda implementação interna de qualquer versão do Windows. Categoria: A) regra conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (338, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Atalhos (.lnk) — nome do tipo de ícone (origem=REAL)', 'ORIGEM: REAL (Fundatec, Corpo de Bombeiros Militar RS - Soldado de Primeira Classe, 2025). FIDELIDADE: reavaliada nesta ordem (constava em lista de pendências históricas de suspeita visual) — a questão pede o NOME do tipo de ícone usado para criar um link rápido, um conceito, sem exigir reconhecimento visual de um ícone específico mostrado em imagem; concluído AUTOSSUFICIENTE_CONFIRMADA. Fenômeno testado: o tipo de ícone usado para link rápido a um programa/arquivo/pasta é o ATALHO (Shortcut, arquivo .lnk, identificável pela seta no canto inferior esquerdo) — gabarito C, distinto de "ponte", "indicador", "ícone" (termo genérico) e "ponteiro" (cursor do mouse). RECORRÊNCIA: atalhos são fenômeno RECORRENTE NESTE CORPUS, confirmado por uma segunda ocorrência independente em Q644 (prova distinta, sobre a dependência do atalho em relação ao arquivo original). Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (339, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Gerenciador de Tarefas — guia Processos (origem=REAL)', 'ORIGEM: REAL (Fundatec, Corpo de Bombeiros Militar RS - Soldado de Primeira Classe, 2025 — mesma prova de Q338). Fenômeno testado: a guia "Processos" do Gerenciador de Tarefas do Windows 10 exibe CPU, memória, disco, rede e GPU por processo, mas NÃO é a guia destinada a listar usuários conectados — essa informação fica na guia separada "Usuários" (gabarito A, EXCETO). RECORRÊNCIA: Gerenciador de Tarefas é fenômeno RECORRENTE NESTE CORPUS, confirmado por uma segunda ocorrência independente em Q494 (prova distinta, guia Desempenho). Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (494, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Gerenciador de Tarefas — guia Desempenho (origem=REAL)', 'ORIGEM: REAL (Fundatec, GM (Pref Foz do Iguaçu)/Pref Foz do Iguaçu, 2024). FIDELIDADE: reavaliada nesta ordem (constava em lista de pendências históricas de suspeita visual) — a questão pede o NOME da guia que apresenta gráficos de hardware em tempo real, um conceito, sem exigir reconhecimento visual de uma tela específica mostrada em imagem; concluído AUTOSSUFICIENTE_CONFIRMADA. Fenômeno testado: a guia DESEMPENHO do Gerenciador de Tarefas apresenta gráficos/métricas em tempo real de CPU, memória, disco, rede e GPU (gabarito B), distinta de Processos (tabela por programa), "Monitoramento" (não existe), Histórico de Aplicativos e Detalhes. RECORRÊNCIA: Gerenciador de Tarefas é fenômeno RECORRENTE NESTE CORPUS (ver Q339, prova independente). Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (643, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Histórico da Área de Transferência (origem=REAL)', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: julgamento de 3 assertivas sobre a área de transferência no Windows 11 — o Histórico da Área de Transferência (Win+V) salva itens recentes copiados/recortados (verdadeiro); Ctrl+C copia texto selecionado (verdadeiro); a área de transferência NÃO suporta imagens é falso, pois ela suporta arquivos de imagem normalmente (gabarito C: V-V-F). CAUTELA DE VERSÃO: questão associada ao Windows 11/época da prova (2026) — não garantir que todo comportamento atual de interface/configuração seja idêntico ao da prova histórica. Categoria: A) regra conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (644, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Atalhos — dependência do arquivo original (origem=REAL)', 'ORIGEM: REAL (Fundatec, GM (Pref Gravataí)/Pref Gravataí, 2026). Fenômeno testado: um atalho (.lnk) é um ponteiro lógico para o arquivo/programa/pasta original — para funcionar corretamente, é indispensável que o original permaneça existindo, íntegro e acessível (gabarito A); o atalho pode ter nome diferente do original, múltiplos atalhos podem apontar para o mesmo arquivo, e não há exigência de criptografia. RECORRÊNCIA: atalhos são fenômeno RECORRENTE NESTE CORPUS (ver Q338, prova independente). CAUTELA: reforça o limite de não simplificar "atalho = arquivo original" — o atalho é referência/ponteiro, não cópia. Categoria: A) regra conceitual. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (645, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Caracteres proibidos em nomes de arquivo/pasta (origem=REAL)', 'ORIGEM: REAL (Fundatec, GM (Pref Araquari)/Pref Araquari, 2026). Fenômeno testado: o caractere ":" é proibido em nomes de pasta no Windows 11 (reservado para identificar unidades de disco e fluxos NTFS) — "Araquari:GuardaMunicipal" é inválido (gabarito B), enquanto nomes com letras, números, sublinhado, hífen, espaço e acentos são válidos. RECORRÊNCIA: este fenômeno é RECORRENTE NESTE CORPUS — Q101 e Q645 são incidências distintas por virem de provas independentes (SUSEPE/Polícia Penal RS 2022 e GM Araquari 2026), sustentando recorrência real. CAUTELA: mesma ressalva de Q101 sobre não generalizar os 9 caracteres proibidos como lista exaustiva de todas as restrições possíveis. Categoria: B) regra factual de produto. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (711, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Associação conceitual — Gerenciador de Tarefas / Área de Trabalho / Painel de Controle (origem=REAL)', 'ORIGEM: REAL (Fundatec, GM (Pref Porto Alegre)/Pref Porto Alegre, 2025). Fenômeno testado: associação de 3 funcionalidades do Windows 10 às suas descrições — Gerenciador de Tarefas (visualiza/gerencia processos e desempenho), Área de Trabalho (interface principal com ícones de acesso rápido) e Painel de Controle (central de configurações do sistema, como adicionar/remover programas) — sequência correta 3-2-1 (gabarito E). RECORRÊNCIA: Painel de Controle é fenômeno RECORRENTE NESTE CORPUS (ver Q103, prova independente). Categoria: A) regra conceitual (associativa). Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (835, '936d2d9d-0f83-4a25-8066-9e035a12ca16'::uuid, 1, 'Propriedades de arquivo — aba Geral (origem=REAL)', 'ORIGEM: REAL (Fundatec, Tec (Pref Viamão)/Pref Viamão/Agrícola, 2022). Fenômeno testado: a aba "Geral" da caixa de diálogo Propriedades de um arquivo no Explorador de Arquivos do Windows 10 exibe tipo, local, tamanho, tamanho em disco, datas de criação/modificação/acesso e atributos, mas NÃO exibe um contador de "número de acessos" ao arquivo (gabarito C, EXCETO). Categoria: B) regra factual de produto. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta')
)
select * from mapa order by questao_id, ordem_unidade;

-- ============================================================================
-- 2) LISTAS EXPLICITAS.
-- ============================================================================

-- 2a) Questoes classificadas (14/15).
-- 31,60,101,102,103,108,338,339,494,643,644,645,711,835

-- 2b) Questoes multiunidade: nenhuma

-- 2c) Questoes excluidas intencionalmente (fora de escopo/pendente de saneamento): 836 (DUPLICATA_Q836 — mesmo enunciado, mesmas 5 alternativas e mesmo gabarito (B) de Q101 ("praia ou serra?.pdf" como nome inválido pelo caractere '?'), mesmo bloco de Informática do concurso SUSEPE/Polícia Penal RS 01/2022 (cargos diferentes, mesma prova de origem). Q836 possui glitch textual "arquivoinválido" (sem espaço), enquanto Q101 é a versão mais limpa e foi escolhida como questão canônica vinculada. Q836 permanece ATIVA, INTACTA e SEM vínculo neste conteúdo — não corrigida, não desativada, não contabilizada como segunda incidência independente do fenômeno de caracteres proibidos.)

-- ============================================================================
-- 3) Cobertura por unidade (questoes distintas). NAO forca nenhuma unidade
--    a atingir 10; unidades fracas sao GAP REAL DO BANCO, nao erro tecnico.
-- ============================================================================
-- U1 Windows: 14 questoes distintas
-- Total de vinculos esperados: 14 (14 questoes distintas
-- + 0 vinculo(s) extra(s) de multiunidade).
