-- Mapa de classificacao semantica das questoes validas de Classes de palavras
-- (curso_conteudos.id = 22, assunto_id = 47,
-- materia_id = 6), gerado pelo pipeline automatico
-- (scripts/curadoria-pedagogica/gerar-mapa.mjs) a partir de
-- config/classes_de_palavras.mapa.json — produto de leitura humana do enunciado + TODAS
-- as alternativas de cada questao (nunca por ID, banca, concurso ou
-- palavra-chave isolada). Mesmo metodo de
-- supabase/mapa_classificacao_improbidade.sql.
--
-- SOMENTE LEITURA. Este arquivo nao escreve nada — e a fonte unica de
-- verdade (mapa aprovado) que
--   classificar_questoes_unidades_classes_de_palavras_teste_rollback.sql
--   classificar_questoes_unidades_classes_de_palavras.sql
-- devem replicar byte a byte na tabela temporaria _mapa antes de aplicar.
--
-- Unidades oficiais do conteudo 22 (apos curadoria_unidades_classes_de_palavras.sql):
--   U1 3f215008-367b-4890-9588-525980baefc1  ordem 1  Classes de palavras
--
-- Resultado da curadoria: 17/21 questoes ativas
-- classificadas, multiunidade: nenhuma, excluidas: 71 (FORA_DE_ESCOPO_SINTAXE_SUJEITO — cobra identificacao de sujeito simples pelo numero de nucleos do sintagma nominal, habilidade de sintaxe (analise do termo sujeito), nao classe de palavra. Provavel destino futuro: conteudo de Sintaxe/Sujeito/Termos da oracao, a confirmar pela fila real. Nao realocada nesta etapa.); 325 (PROBLEMA_DE_DADO_TEXTO_BASE_AUSENTE — gabarito e regra confirmados pelo usuario via fonte externa (FUNDATEC/Prefeitura de Esteio/2022): 'que essa acao' e conjuncao integrante ligada a 'compreenda' ('...para que se compreenda que essa acao e o que estrutura a essencia da sociedade'). Confianca linguistica alta no gabarito E. Porem o texto-base necessario para o aluno resolver a questao autonomamente nao esta armazenado no banco. Candidata prioritaria a saneamento futuro (texto original recuperavel); texto nao restaurado neste apply.); 683 (FORA_DE_ESCOPO_REFERENCIA_TEXTUAL — cobra predominantemente referencia anaforica ('Ele' retomando 'bem comum') e reiteracao lexical do texto, habilidade de coesao/referenciacao/interpretacao textual, nao classificacao morfologica. Provavel destino futuro: coesao/referenciacao/interpretacao textual, a confirmar. Nao realocada nesta etapa.); 878 (FORA_DE_ESCOPO_SEMANTICA_PRESSUPOSICAO — cobra pressuposicao semantica associada a 'novos' (novos recordes pressupoe recordes anteriores), predominantemente semantica/pragmatica/interpretacao, nao classificacao morfologica da palavra 'novos'. Provavel destino futuro: semantica/interpretacao textual, a confirmar. Nao realocada nesta etapa.).

-- ============================================================================
-- 1) MAPA — uma linha por vinculo (questao multiunidade = mais de uma linha).
-- ============================================================================
with mapa (questao_id, unidade_pedagogica_id, ordem_unidade, tema, justificativa, confianca) as (
  values
    (273, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo B — ''bastante'' advérbio × pronome indefinido', 'Regra testada: em ''Os candidatos estudaram bastante'', ''bastante'' modifica o verbo ''estudaram'' (sentido de intensidade), classificando-se como advérbio, permanecendo invariável. Categoria: D) contraste morfológico (advérbio invariável ''bastante'' ligado a verbo × pronome indefinido variável ''bastante(s)'' ligado a substantivo, ex.: ''leram bastantes livros''). Distratores trocam por substantivo, artigo, preposição, pronome relativo.', 'alta'),
    (274, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — pronome demonstrativo ''aquela''', 'Regra testada: ''aquela'' acompanha o substantivo ''prova'', situando-o no espaço/discurso como distante do emissor e do receptor — pronome demonstrativo (adjetivo). Categoria: B) regra morfológica. Distratores trocam por advérbio, conjunção, preposição, substantivo.', 'alta'),
    (323, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — contagem de artigos definidos vs. pronome oblíquo', 'Regra testada: no trecho, há 2 artigos definidos (''o recolher-se'', artigo substantivador do infinitivo; ''o novo momento'', artigo comum); o ''o'' de ''tal fato o leva'' é PRONOME OBLÍQUO ÁTONO (equivale a ''leva-o''/''leva ele''), não artigo. Categoria: D) contraste morfológico (artigo × pronome oblíquo homônimo). Verificado independentemente: infinitivo substantivado precedido de artigo é construção gramatical válida em português (''o recolher-se'', análogo a ''o andar'', ''o comer'').', 'alta'),
    (330, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo C — ''extremidades'' como substantivo (com nota de ortografia/sinonímia secundárias)', 'Regra testada (foco desta unidade): ''extremidades'' é substantivo (não adjetivo) na oração. A questão também testa, secundariamente, grafia (letra ''x'') e sinonímia (''pontas'') — pontos incidentais a este conteúdo, já que o eixo aqui é classe de palavras. Categoria: B) regra morfológica. Distratores classificam a palavra como adjetivo.', 'alta'),
    (331, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo B — circunstâncias adverbiais: tempo, lugar, intensidade', 'Regra testada: ''a partir do século XVI'' = circunstância de tempo; ''na Inglaterra'' = lugar; ''mais desenvolvidas'' (''mais'' modificando o adjetivo ''desenvolvidas'') = intensidade. Categoria: A) regra produtiva (pergunta-guia: quando?/onde?/quanto?). Distratores trocam tempo↔modo, lugar↔tempo, intensidade↔afirmação.', 'alta'),
    (335, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo C — substantivo/preposição/substantivo (combate/em/bronze)', 'Regra testada: ''combate'' é substantivo (não verbo) em ''mangueira de combate a incêndio''; ''em'' é preposição essencial (não conjunção); ''bronze'' é substantivo (não adjetivo). Categoria: B) regra morfológica (classe depende da função no sintagma, mesma forma pode ser substantivo ou verbo). Distratores trocam substantivo por verbo/adjetivo, e preposição por conjunção.', 'alta'),
    (682, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A + Eixo B — advérbio/pronome relativo/adjetivo/pronome indefinido (infelizmente/que/integral/cada)', 'Regras testadas: (1) ''infelizmente'' = advérbio de modo, na nomenclatura tradicional adotada pela banca (Fundatec) — CATEGORIA B, regra morfológica; nota pedagógica registrada: abordagens gramaticais contemporâneas podem classificar advérbios avaliativos como ''infelizmente'' de forma distinta (modalizador incidindo sobre todo o enunciado), mas a classificação tradicional é a exigida aqui, e a futura aula deve ensinar o aluno a identificar o padrão teórico da banca antes de classificar; (2) ''que'' = pronome relativo, retomando o antecedente ''circunstâncias'' — categoria D, contraste com conjunção; (3) ''integral'' = adjetivo, qualifica ''desenvolvimento'' — categoria B; (4) ''cada'' = pronome indefinido (nunca numeral) — categoria B. Questão compartilhada entre os Eixos A (itens 2 e 4) e B (item 1).', 'alta'),
    (684, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — pronome relativo possessivo ''cujos''', 'Regra testada: ''cujos'' é pronome relativo possessivo que retoma semanticamente o possuidor antecedente (''adolescentes''), concordando em gênero/número com o elemento possuído que vem depois (''relógios biológicos''). Categoria: A) regra produtiva (regra do ''cujo'': sempre retoma o possuidor, concorda com o possuído). Distratores atribuem a retomada ao termo possuído ou a outros elementos da oração.', 'alta'),
    (749, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo C — palavra primitiva de ''sintomático''', 'Regra testada: ''sintomático'' é palavra derivada por sufixação a partir da palavra primitiva ''sintoma'' (sintoma + -ático). Categoria: B) regra morfológica (primitiva × derivada). Distratores propõem palavras foneticamente parecidas mas sem relação etimológica real (síncrono, sístole, sino, sinal).', 'alta'),
    (750, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — ''o'' como pronome demonstrativo, artigo definido e elemento de contração', 'Regras testadas: (1) ''o'' antes de ''que'' (em ''sabemos o que a palavra significa'') = pronome demonstrativo (equivale a ''aquilo''); (2) ''o'' antes de substantivo (''divide o problema'', ''forçar o outro'') = artigo definido; (3) ''a'' em ''ao alvo'' é contração da preposição ''a'' com o artigo MASCULINO ''o'' (não com o artigo feminino ''a'', já que ''alvo'' é substantivo masculino) — a assertiva III do enunciado está INCORRETA por erro de gênero. Categoria: D) contraste múltiplo (pronome demonstrativo × artigo × contração).', 'alta'),
    (751, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — pronome demonstrativo e pronome relativo retomando antecedentes (com nota sobre anáfora/catáfora)', 'Regras testadas (foco desta unidade): (1) ''aqueles'' é pronome demonstrativo que retoma o antecedente ''funcionários''; (2) a segunda ocorrência de ''que'' é pronome relativo que retoma o antecedente ''colaboradores''. A questão também testa, na assertiva III, a distinção anáfora (''Isso'' retoma o que já foi dito) × catáfora (seria ''Isto'', seria dependência textual), que é habilidade adjacente de referenciação textual, mencionada aqui apenas como contexto para explicar o funcionamento do pronome demonstrativo, sem se tornar eixo autônomo. Categoria: D) contraste morfológico (itens 1 e 2) + E) habilidade textual (item 3, secundário).', 'alta'),
    (752, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo C — adjetivo e suas flexões (número e gênero)', 'Regra testada: ''incrédulos'' é adjetivo, varia em número e gênero (não em tempo/pessoa/modo, exclusivos do verbo). Categoria: A) regra produtiva (flexões nominais × flexões verbais). Distratores atribuem à palavra flexões típicas de verbo.', 'alta'),
    (784, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo B — advérbio de dúvida ''talvez''', 'Regra testada: ''talvez'' classifica-se como advérbio de dúvida, expressando incerteza/eventualidade quanto à ocorrência da ação verbal. Categoria: C) grafia/uso lexical (lista fechada de advérbios de dúvida a memorizar: talvez, quiçá, porventura, acaso, provavelmente). Distratores trocam por afirmação, negação, modo, lugar.', 'alta'),
    (806, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo C — ''intragável'' como adjetivo, formação com prefixo in- e uniformidade de gênero', 'Regras testadas: (1) ''intragável'' é adjetivo; (2) suprimindo o prefixo ''in-'', obtém-se ''tragável'' (adjetivo derivado do verbo ''tragar'', que se pode tragar), palavra que EXISTE na língua — confirmado pelo usuário, sem ressalva lexicográfica, confiança alta; (3) adjetivo uniforme quanto ao gênero (mesma forma para masculino e feminino: ''comportamento intragável''/''atitude intragável''), variando apenas em número (intragável/intragáveis). Categoria: B) regra morfológica (formação de palavras por prefixação + flexão de adjetivos uniformes).', 'alta'),
    (876, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo C — ''graves'' como adjetivo', 'Regra testada: ''graves'' qualifica o substantivo ''doenças'' (''doenças graves''), funcionando morfologicamente como adjetivo (não advérbio, que seria invariável, nem função sintática de objeto). Categoria: B) regra morfológica. Distratores confundem classe morfológica com função sintática (objeto direto/indireto) ou com advérbio.', 'alta'),
    (877, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — contagem de artigos definidos incluindo contrações com preposições', 'Regra testada: no trecho legal citado, há exatamente 8 artigos definidos, contando tanto os simples (''O'', ''a'', ''os'') quanto os contraídos com preposição (''do''=de+o, ''da''=de+a, ''das''=de+as, ''na''=em+a). Categoria: A) regra produtiva (identificação sistemática de artigo e suas contrações — mesmo fenômeno gramatical de Q323, por isso classificada no mesmo eixo). NOTA DE QUALIDADE DE DADO: esta questão possui apenas 4 alternativas no banco (não 5); não foi encontrada evidência de truncamento ou alternativa ausente — a explicação armazenada é completa e coerente para as 4 alternativas presentes (5, 6, 7, 8), sem qualquer menção a uma 5ª. Classificada normalmente, sem inventar alternativa.', 'alta'),
    (879, '3f215008-367b-4890-9588-525980baefc1'::uuid, 1, 'Eixo A — pronome demonstrativo ''Esta'' como adjunto adnominal', 'Regra testada: ''Esta'' é pronome demonstrativo adjetivo que acompanha e determina o substantivo ''abordagem'', exercendo função sintática de adjunto adnominal; é também anafórico (retoma a estratégia descrita imediatamente antes no texto). Categoria: B) regra morfológica + D) contraste (pronome adjetivo × pronome substantivo).', 'alta')
)
select * from mapa order by questao_id, ordem_unidade;

-- ============================================================================
-- 2) LISTAS EXPLICITAS.
-- ============================================================================

-- 2a) Questoes classificadas (17/21).
-- 273,274,323,330,331,335,682,684,749,750,751,752,784,806,876,877,879

-- 2b) Questoes multiunidade: nenhuma

-- 2c) Questoes excluidas intencionalmente (fora de escopo/pendente de saneamento): 71 (FORA_DE_ESCOPO_SINTAXE_SUJEITO — cobra identificacao de sujeito simples pelo numero de nucleos do sintagma nominal, habilidade de sintaxe (analise do termo sujeito), nao classe de palavra. Provavel destino futuro: conteudo de Sintaxe/Sujeito/Termos da oracao, a confirmar pela fila real. Nao realocada nesta etapa.); 325 (PROBLEMA_DE_DADO_TEXTO_BASE_AUSENTE — gabarito e regra confirmados pelo usuario via fonte externa (FUNDATEC/Prefeitura de Esteio/2022): 'que essa acao' e conjuncao integrante ligada a 'compreenda' ('...para que se compreenda que essa acao e o que estrutura a essencia da sociedade'). Confianca linguistica alta no gabarito E. Porem o texto-base necessario para o aluno resolver a questao autonomamente nao esta armazenado no banco. Candidata prioritaria a saneamento futuro (texto original recuperavel); texto nao restaurado neste apply.); 683 (FORA_DE_ESCOPO_REFERENCIA_TEXTUAL — cobra predominantemente referencia anaforica ('Ele' retomando 'bem comum') e reiteracao lexical do texto, habilidade de coesao/referenciacao/interpretacao textual, nao classificacao morfologica. Provavel destino futuro: coesao/referenciacao/interpretacao textual, a confirmar. Nao realocada nesta etapa.); 878 (FORA_DE_ESCOPO_SEMANTICA_PRESSUPOSICAO — cobra pressuposicao semantica associada a 'novos' (novos recordes pressupoe recordes anteriores), predominantemente semantica/pragmatica/interpretacao, nao classificacao morfologica da palavra 'novos'. Provavel destino futuro: semantica/interpretacao textual, a confirmar. Nao realocada nesta etapa.)

-- ============================================================================
-- 3) Cobertura por unidade (questoes distintas). NAO forca nenhuma unidade
--    a atingir 10; unidades fracas sao GAP REAL DO BANCO, nao erro tecnico.
-- ============================================================================
-- U1 Classes de palavras: 17 questoes distintas
-- Total de vinculos esperados: 17 (17 questoes distintas
-- + 0 vinculo(s) extra(s) de multiunidade).
