-- Mapa de classificacao semantica das questoes validas de Ortografia
-- (curso_conteudos.id = 20, assunto_id = 53,
-- materia_id = 6), gerado pelo pipeline automatico
-- (scripts/curadoria-pedagogica/gerar-mapa.mjs) a partir de
-- config/ortografia.mapa.json — produto de leitura humana do enunciado + TODAS
-- as alternativas de cada questao (nunca por ID, banca, concurso ou
-- palavra-chave isolada). Mesmo metodo de
-- supabase/mapa_classificacao_improbidade.sql.
--
-- SOMENTE LEITURA. Este arquivo nao escreve nada — e a fonte unica de
-- verdade (mapa aprovado) que
--   classificar_questoes_unidades_ortografia_teste_rollback.sql
--   classificar_questoes_unidades_ortografia.sql
-- devem replicar byte a byte na tabela temporaria _mapa antes de aplicar.
--
-- Unidades oficiais do conteudo 20 (apos curadoria_unidades_ortografia.sql):
--   U1 dc6d39fb-5600-43d4-bad6-e3de2356236d  ordem 1  Ortografia
--
-- Resultado da curadoria: 22/24 questoes ativas
-- classificadas, multiunidade: nenhuma, excluidas: 688 (PROBLEMA_DE_DADO_LACUNAS_AUSENTES — o enunciado armazenado perdeu os marcadores de lacuna originais (a mesma passagem, preservada em Q683, mostra marcadores de posicao I)/II)/III) apos as palavras ja resolvidas concepcao/dimensao/caos, que coincidem com o gabarito de Q688, mas a estrutura exata de onde cortar cada palavra para reconstituir as lacunas nao foi recuperada de forma inequivoca). Nao reconstruido artificialmente. Forte evidencia disponivel para saneamento futuro.); 689 (DUPLICATA_EXATA_DE_Q321 — mesmo enunciado, mesmas 5 alternativas na mesma ordem, mesmo gabarito (s-x-s-z). Q321 mantida como classificacao canonica.).

-- ============================================================================
-- 1) MAPA — uma linha por vinculo (questao multiunidade = mais de uma linha).
-- ============================================================================
with mapa (questao_id, unidade_pedagogica_id, ordem_unidade, tema, justificativa, confianca) as (
  values
    (66, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — G/J, S/Z, SC em coragem/amenizar/fascínio', 'Regra testada: grafia consagrada de ''coragem''(g), ''amenizar''(z), ''fascínio''(sc). Categoria: C) grafia lexical. Fonte: VOLP/grafia consagrada. Distratores trocam g/j, s/z, sc/c/s isoladamente.', 'alta'),
    (119, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — mordazes/trás×traz/ruborizando/quisermos', 'Regras testadas: (1) ''mordazes'', plural de ''mordaz'' com z (categoria B, regra morfológica de plural mantendo a consoante do singular); (2) contraste ''trás'' (advérbio de lugar, grafado com S e acento agudo — NÃO chamar de ''acento diferencial''; contraste é gráfico/semântico/morfológico, categoria D) × ''traz'' (forma do verbo trazer, com Z, sem acento); (3) ''ruborizando'', gerúndio de ''ruborizar'' com -izar (categoria B); (4) ''quisermos'', futuro do subjuntivo de querer, sempre com S etimológico (categoria B, nunca Z: quis, quiser, quisesse, quisermos). Fonte: gramática normativa/VOLP.', 'alta'),
    (307, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — grafia lexical de ''exceção''', 'Regra testada: grafia fixa de ''exceção'' (com X+C, não SS). Categoria: C) grafia lexical. Distratores duplicam S ou omitem o X.', 'alta'),
    (321, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — S/X/Z em desempenho/exigente/esgotamento/visualizado', 'Regra testada: grafia consagrada de ''desempenho''(s), ''exigente''(x), ''esgotamento''(s), ''visualizado''(z, verbo -izar). Categoria: C) grafia lexical + B) regra morfológica (verbo -izar). QUESTÃO CANÔNICA — Q689 é duplicata exata desta questão (ver questoes_excluidas) e permanece sem vínculo.', 'alta'),
    (322, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — verbos -isar × -izar e grafia lexical (ascensão, pretensioso)', 'Regra testada: ''paralisar'' (verbo formado de base em -isia/-iso, com S — categoria B, regra morfológica) em contraste com ''utilizar'' (com Z); ''ascensão'' (com S, não Ç) e ''pretensioso'' (com S, não C) — categoria C, grafia lexical. Distratores exploram a confusão sistemática -isar/-izar.', 'alta'),
    (329, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — X/Ç/Z em deixar/extinção/utilizar', 'Regra testada: grafia consagrada de ''deixar''(x), ''extinção''(ç), ''utilizar''(z, verbo -izar). Categoria: C) grafia lexical + B) regra morfológica.', 'alta'),
    (690, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — dígrafo SC em ''acréscimo''', 'Regra testada: dígrafo ''SC'' representando o fonema /s/ em ''acréscimo'', contrastado com SS (''assistir''), XC (''excesso''), SS (''dissimular'') e CI (''suficiente'') nos distratores. Categoria: C) grafia lexical.', 'alta'),
    (691, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo B — hífen: recém-nascido correto vs. distratores de Base XV e XVI', 'Regra testada (gabarito): ''recém-nascido'', hífen sempre obrigatório com o elemento ''recém-'' — Base XV do Acordo Ortográfico. Categoria: A) regra produtiva. Distratores: ''bem estar'' (deveria ser ''bem-estar'', Base XV, ''bem''+vogal=hífen), ''pré vestibular'' (deveria ser ''pré-vestibular'', Base XVI, prefixo tônico ''pré-''), ''fim-de-semana'' (deveria ser ''fim de semana'', Base XV, locução substantiva que perdeu o hífen no Acordo), ''ex namorado'' (deveria ser ''ex-namorado'', Base XVI, prefixo ''ex-'' sempre hifenizado).', 'alta'),
    (758, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — C/X em celeiro/exposta/enxerga (texto ''Modo Avião'')', 'Regra testada: ''celeiro'' (C inicial), ''exposta'' (X), ''enxerga'' (X após EN-). Categoria: C) grafia lexical.', 'alta'),
    (759, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — despercebida/autodirigida/subsistência/mexe (texto ''Violência'')', 'Regras testadas: (1) ''despercebida'' (que não é notada) × ''desapercebida'' (desprovida/desprevenida) — parônimos com sentidos diferentes, categoria D; (2) ''autodirigida'', prefixo ''auto-'' sem hífen diante de consoante diferente de R/S — Base XVI do Acordo Ortográfico, mencionada aqui apenas como contexto morfológico (categoria B), não incluída em artigos_esperados; (3) ''subsistência'', grafada com UM ÚNICO S medial (correção aplicada: NÃO existe SS nesse ponto — os erros comuns são duplicar o S ou inserir vogal espúria, ''subssistência''/''subisistência'') — categoria C, grafia lexical; (4) ''mexe'', forma do verbo mexer, sempre com X após ME- (mexer, mexerica, mexilhão; exceção: ''mecha'' de cabelo) — categoria C.', 'alta'),
    (760, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — G/C/SS em exige/incitando/inacessível (texto capacitação digital)', 'Regra testada: ''exige''(g), ''incitando''(c), ''inacessível''(ss). Categoria: C) grafia lexical.', 'alta'),
    (761, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — SS/S/X em obsessão/redes/êxtase (texto ''Anda raro'')', 'Regra testada: ''obsessão''(ss), ''redes''(s), ''êxtase''(x). Categoria: C) grafia lexical.', 'alta'),
    (762, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo B — hífen: ''auto-escola'' incorreto (Base XVI) vs. distratores de Base XVI e XV', 'Regra testada (gabarito): ''auto-escola'' está INCORRETO — a grafia correta é ''autoescola'', pois o prefixo ''auto-'' termina em vogal diferente da vogal com que se inicia o segundo elemento (''o''+''e'') — Base XVI do Acordo Ortográfico (citado explicitamente no enunciado: Decreto nº 6.583/2008). Categoria: A) regra produtiva. Distratores corretos por contraste: ''micro-ônibus'' e ''anti-inflamatório'' (Base XVI, vogal IGUAL = com hífen: o+o, i+i), ''pré-história'' (Base XVI, prefixo tônico ''pré-'' + segundo elemento com H), ''bem-vindo'' (Base XV, composto consolidado/lexicalizado com ''bem'', não pela regra geral de vogal/consoante).', 'alta'),
    (786, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — grafia geral + acentuação de paroxítonas em -L (lavável)', 'Regra testada: ''chaveiro'' correto (dígrafo ch, ditongo ei, sem acento por ser paroxítona terminada em -o); distratores corrigem ''bicicleta''(l, não r), ''vacina''(paroxítona em -a, sem acento), ''presença''(ç, não ss) e, principalmente, ''lavável'' — REGRA CORRIGIDA: paroxítonas terminadas em -L recebem acento agudo obrigatório (lavável, amável, responsável, sensível, fácil, útil); a terminação ''-vel'' é apenas a superfície morfológica mais comum dessa classe, não a regra em si. Categoria: A) regra produtiva (acentuação de paroxítonas em -L) + C) grafia lexical nas demais palavras.', 'alta'),
    (787, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — Ç/S em inspeções/tensão/trás (texto ''Segurança'')', 'Regra testada: ''inspeções''(ç), ''tensão''(s), ''trás'' (advérbio de lugar, ''banco de trás'', com S e acento agudo). Categoria: C) grafia lexical + D) contraste trás×traz reforçado.', 'alta'),
    (809, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo B — hífen: malfeito sem hífen (Base XV) vs distratores de Base XVI', 'Regra testada (gabarito): ''malfeito'', escrito em uma única palavra, sem hífen, porque ''mal'' só exige hífen diante de palavra iniciada por VOGAL ou H; diante de consoante (f, p, c) escreve-se junto — Base XV do Acordo Ortográfico (compostos com bem/mal). Categoria: A) regra produtiva. Distratores ilustram Base XVI: ''pró-alfabetização'' (prefixo tônico ''pró-'', hífen obrigatório), ''inter-racial'' (consoante repetida r+r, hífen obrigatório), ''neo-holandês'' (segundo elemento com H, hífen obrigatório), ''micro-ondas'' (vogal igual o+o, hífen obrigatório).', 'alta'),
    (810, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — SC/X/G em adolescente/exclusão/digere (texto ''Uma advertência'')', 'Regra testada: ''adolescente''(sc), ''exclusão''(x), ''digere''(g, do verbo digerir). Categoria: C) grafia lexical.', 'alta'),
    (888, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — S/SS/Z em previsão/ressaltar/realizando (texto ''Vacina contra dengue'')', 'Regra testada: ''previsão''(s), ''ressaltar''(ss), ''realizando''(z, verbo -izar). Categoria: C) grafia lexical + B) regra morfológica.', 'alta'),
    (889, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — XC/C/Ç em exceção/coercitivas/alicerçada (texto ''Medidas protetivas'')', 'Regra testada: ''exceção''(xc), ''coercitivas''(c), ''alicerçada''(ç). Categoria: C) grafia lexical. NOTA DE QUALIDADE DE DADO: esta questão possui apenas 4 alternativas no banco (não 5, como a maioria das demais). Não foi encontrada evidência de truncamento ou alternativa ausente nos dados disponíveis — a explicação armazenada é completa e coerente para as 4 alternativas presentes, referente à mesma prova/concurso de Q890 (Fundatec, SEJUSP MG 2022), com gerada_por_ia=false. Classificada normalmente, sem inventar quinta alternativa.', 'alta'),
    (890, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo B — hífen: mal-educado com hífen suprimido incorretamente (Base XV) vs distratores de Base XVI', 'Regra testada (gabarito): ''Maleducado'' está com o hífen suprimido INCORRETAMENTE — ''mal'' exige hífen obrigatório diante de palavra iniciada por VOGAL ou H, logo a grafia correta é ''mal-educado'' — Base XV do Acordo Ortográfico. Categoria: A) regra produtiva. Distratores ilustram Base XVI: ''contrassenso'' (prefixo ''contra-'' + palavra iniciada por S = duplica o S, sem hífen), ''autoimagem'' (''auto-'' + vogal diferente o/i = sem hífen), ''reescrita'' (prefixo ''re-'' sempre junta, mesmo diante de vogal igual). NOTA DE QUALIDADE DE DADO: esta questão possui apenas 4 alternativas no banco. Não foi encontrada evidência de truncamento ou alternativa ausente nos dados disponíveis — explicação completa e coerente, mesma prova/concurso de Q889, gerada_por_ia=false. Classificada normalmente, sem inventar quinta alternativa.', 'alta'),
    (891, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — consecutivo/homicídios/hesitaram (texto ''Três anos de um RS mais seguro'')', 'Regra testada: ''consecutivo'' (S simples, não ''conce-''); ''homicídios'' (plural regular em -io, não ''-eos''); ''hesitaram'', do verbo HESITAR (ficar em dúvida, vacilar, titubear — com H e S) em contraste com o verbo parônimo EXITAR (obter êxito, sentido diferente, com X). CORREÇÃO APLICADA: não se trata de ''H mudo aportuguesado'' — é uma grafia lexical (categoria C) com contraste semântico entre dois verbos parônimos distintos (categoria D); o objetivo da questão é reconhecer a grafia e o sentido adequados de ''hesitar'', não uma regra de H mudo.', 'alta'),
    (892, 'dc6d39fb-5600-43d4-bad6-e3de2356236d'::uuid, 1, 'Eixo A — enxurrada/rupturas/reduzi (texto ''mudança climática'')', 'Regra testada: ''enxurrada'' (com X, não CH); ''rupturas'' (sem ''i'' epentético, não ''rupitura''); ''reduzi'' (1ª pessoa do pretérito perfeito, sem acento — ''eu reduzi'', diferente de ''reduzí'' que seria incorreto). Categoria: C) grafia lexical + A) regra produtiva (não acentuar a 1ª pessoa do pretérito perfeito de verbos regulares terminados em -ir/-uzir).', 'alta')
)
select * from mapa order by questao_id, ordem_unidade;

-- ============================================================================
-- 2) LISTAS EXPLICITAS.
-- ============================================================================

-- 2a) Questoes classificadas (22/24).
-- 66,119,307,321,322,329,690,691,758,759,760,761,762,786,787,809,810,888,889,890,891,892

-- 2b) Questoes multiunidade: nenhuma

-- 2c) Questoes excluidas intencionalmente (fora de escopo/pendente de saneamento): 688 (PROBLEMA_DE_DADO_LACUNAS_AUSENTES — o enunciado armazenado perdeu os marcadores de lacuna originais (a mesma passagem, preservada em Q683, mostra marcadores de posicao I)/II)/III) apos as palavras ja resolvidas concepcao/dimensao/caos, que coincidem com o gabarito de Q688, mas a estrutura exata de onde cortar cada palavra para reconstituir as lacunas nao foi recuperada de forma inequivoca). Nao reconstruido artificialmente. Forte evidencia disponivel para saneamento futuro.); 689 (DUPLICATA_EXATA_DE_Q321 — mesmo enunciado, mesmas 5 alternativas na mesma ordem, mesmo gabarito (s-x-s-z). Q321 mantida como classificacao canonica.)

-- ============================================================================
-- 3) Cobertura por unidade (questoes distintas). NAO forca nenhuma unidade
--    a atingir 10; unidades fracas sao GAP REAL DO BANCO, nao erro tecnico.
-- ============================================================================
-- U1 Ortografia: 22 questoes distintas
-- Total de vinculos esperados: 22 (22 questoes distintas
-- + 0 vinculo(s) extra(s) de multiunidade).
