-- Mapa de classificacao semantica das questoes validas de Segurança da informação
-- (curso_conteudos.id = 40, assunto_id = 10,
-- materia_id = 9), gerado pelo pipeline automatico
-- (scripts/curadoria-pedagogica/gerar-mapa.mjs) a partir de
-- config/seguranca_da_informacao.mapa.json — produto de leitura humana do enunciado + TODAS
-- as alternativas de cada questao (nunca por ID, banca, concurso ou
-- palavra-chave isolada). Mesmo metodo de
-- supabase/mapa_classificacao_improbidade.sql.
--
-- SOMENTE LEITURA. Este arquivo nao escreve nada — e a fonte unica de
-- verdade (mapa aprovado) que
--   classificar_questoes_unidades_seguranca_da_informacao_teste_rollback.sql
--   classificar_questoes_unidades_seguranca_da_informacao.sql
-- devem replicar byte a byte na tabela temporaria _mapa antes de aplicar.
--
-- Unidades oficiais do conteudo 40 (apos curadoria_unidades_seguranca_da_informacao.sql):
--   U1 a042af68-babf-4385-bcc4-2fa69e9b27cd  ordem 1  Segurança da informação
--
-- Resultado da curadoria: 13/13 questoes ativas
-- classificadas, multiunidade: nenhuma, excluidas: nenhuma.

-- ============================================================================
-- 1) MAPA — uma linha por vinculo (questao multiunidade = mais de uma linha).
-- ============================================================================
with mapa (questao_id, unidade_pedagogica_id, ordem_unidade, tema, justificativa, confianca) as (
  values
    (11, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Phishing (cobertura suplementar; origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO (banca="Papiro — estilo FGV", concurso="Polícia Civil do Paraná", ano=NULL) — PROBLEMA_DE_QUALIDADE_METADADOS_Q11 registrado (banca em formato/estilo divergente do padrão majoritário do curso), sinalizado e NÃO corrigido nesta curadoria; independente disso, o conteúdo pedagógico da questão é correto e vinculável como material suplementar de prática, sem contar para incidência histórica, recorrência, frequência Fundatec ou recência — registrada como COBERTURA_SUPLEMENTAR_SEGURANCA_DA_INFORMACAO. NOTA: o campo `explicacao` desta questão foi corrigido em operação de saneamento de fidelidade separada e já commitada (commit cab1779) — o enunciado, as alternativas e o gabarito ("Phishing", ordem 1) permaneceram inalterados; apenas o texto de justificativa, antes desconectado do enunciado, foi reescrito para corresponder à habilidade realmente testada. Nenhum novo saneamento foi feito nesta curadoria. Fenômeno testado: mensagem eletrônica que imita instituição legítima para induzir o usuário a informar senha caracteriza PHISHING, técnica de engenharia social — distinta de backup incremental, firewall de aplicação e criptografia assimétrica. GAP_DE_PRATICA_ESPECIFICA_REAL_PHISHING: nenhuma questão REAL deste corpus testa phishing — a prática disponível é integralmente autoral (ver também Q294). Categoria: B) regra factual/conceitual. Explicação armazenada NÃO alterada nesta curadoria (já havia sido corrigida em operação anterior separada).', 'alta'),
    (15, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Autenticação em dois fatores (cobertura suplementar; origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO (banca="Papiro — estilo Fundatec", concurso="Brigada Militar do Rio Grande do Sul", ano=NULL) — material suplementar de prática, NÃO conta para incidência histórica, recorrência, frequência Fundatec ou recência — registrada como COBERTURA_SUPLEMENTAR_SEGURANCA_DA_INFORMACAO. NOTA: o campo `explicacao` desta questão foi corrigido em operação de saneamento de fidelidade separada e já commitada (commit cab1779) — o enunciado, as alternativas e o gabarito ("Ativar autenticação em dois fatores", ordem 1) permaneceram inalterados; apenas o texto de justificativa, antes desconectado (falava de senha forte com troca periódica, conceito ausente das alternativas), foi reescrito para corresponder à habilidade realmente testada. Nenhum novo saneamento foi feito nesta curadoria. Fenômeno testado: ativar a autenticação em dois fatores (2FA) é a prática que mais aumenta a segurança de uma conta, exigindo uma segunda etapa de verificação de fator diferente da senha — distinta de reutilizar senha, compartilhar senha e desativar atualizações automáticas. Categoria: A) regra conceitual. Explicação armazenada NÃO alterada nesta curadoria (já havia sido corrigida em operação anterior separada).', 'alta'),
    (32, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Autenticação em dois fatores (cobertura suplementar; origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO (banca="Papiro - estilo Fundatec", concurso="Brigada Militar do Rio Grande do Sul", ano=NULL) — material suplementar de prática, NÃO conta para incidência histórica, recorrência, frequência Fundatec ou recência — registrada como COBERTURA_SUPLEMENTAR_SEGURANCA_DA_INFORMACAO. Não é duplicata de Q15: são duas questões autorais distintas sobre a mesma habilidade (2FA/MFA), sem evidência de mesma questão-fonte. Fenômeno testado: a medida que adiciona uma segunda verificação além da senha ao acessar uma conta é a Autenticação em Dois Fatores (2FA/MFA), combinando algo que se sabe (senha) com algo que se tem (token/app autenticador) ou que se é (biometria) — distinta de compactação de arquivos, navegação anônima, desfragmentação de disco e limpeza de histórico. Categoria: A) regra conceitual. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (294, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Phishing (cobertura suplementar; origem=AUTORAL_PAPIRO)', 'ORIGEM: AUTORAL_PAPIRO (banca="Papiro", concurso="PAPIRO - Adaptada do padrão Fundatec 2025/2026", ano=2026 — banca="Papiro" decide a classificação como autoral independentemente do ano preenchido ou da nota "adaptada do padrão Fundatec") — material suplementar de prática, NÃO conta para incidência histórica, recorrência, frequência Fundatec ou recência — registrada como COBERTURA_SUPLEMENTAR_SEGURANCA_DA_INFORMACAO. Não é duplicata de Q11: são duas questões autorais distintas sobre a mesma habilidade (phishing), sem evidência de mesma questão-fonte (alternativas diferentes: Q11 tem 4 opções incluindo "Criptografia assimétrica"; Q294 tem 5 opções incluindo "Compactação" e "Desfragmentação"). Fenômeno testado: mensagem eletrônica fraudulenta que tenta induzir o usuário a fornecer senhas/dados bancários caracteriza PHISHING — distinta de backup, firewall, compactação e desfragmentação. GAP_DE_PRATICA_ESPECIFICA_REAL_PHISHING: nenhuma questão REAL deste corpus testa phishing (ver também Q11). Categoria: B) regra factual/conceitual. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (639, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Spoofing (origem=REAL)', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026). Fenômeno testado: SPOOFING é a técnica de falsificação/mascaramento de identidade ou origem (IP, e-mail, DNS, ARP), forjando cabeçalhos/identidades para se passar por fonte confiável (gabarito D) — distinto de força bruta (tentativa e erro para adivinhar senha), worm (autorreplicação sem hospedeiro), DDoS (sobrecarga distribuída) e ransomware (extorsão via criptografia de arquivos). Não tratar spoofing como sinônimo genérico de qualquer ataque. Categoria: A) regra conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (640, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Autenticação multifator moderna (origem=REAL)', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026 — mesma prova de Q639). Fenômeno testado: é INCORRETO afirmar que o primeiro fator de autenticação multifator (MFA) deva ser obrigatoriamente uma senha tradicional (gabarito D) — sistemas modernos permitem autenticação iniciando por dados biométricos (fator de inerência) ou chave física (fator de posse), sem exigência prévia de senha digitada (login passwordless/FIDO2/passkeys). CAUTELA: o ponto central é que senha NÃO é requisito universal do primeiro fator — não transformar isso na afirmação de que "senha não é mais usada". Demais assertivas da questão (combinação de dois+ fatores distintos; camada adicional de proteção; fatores de categorias diferentes são mais seguros que fatores da mesma categoria; OTP por SMS/e-mail como fator de posse) estão corretas e reforçam a distinção CONHECIMENTO/POSSE/INERÊNCIA — duas senhas continuam sendo o mesmo fator (conhecimento), não configurando multifator. Categoria: A) regra conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (641, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Criptografia simétrica (origem=REAL)', 'ORIGEM: REAL (Fundatec, Esc Pol (PC RS)/PC RS, 2026 — mesma prova de Q639/Q640). Fenômeno testado: a criptografia SIMÉTRICA usa a mesma chave secreta/compartilhada tanto para cifrar quanto para decifrar uma informação (gabarito E, ex.: AES, DES, 3DES, RC4) — distinta da ASSIMÉTRICA (par de chaves relacionadas: pública cifra, privada decifra, ex.: RSA, ECC). "Central" e "Principal" não são modalidades técnicas de chave criptográfica. Categoria: B) regra factual/conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (642, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Sintomas de malware (origem=REAL)', 'ORIGEM: REAL (Fundatec, GM (Pref Araquari)/Pref Araquari, 2026). Fenômeno testado: lentidão excessiva do sistema somada à abertura espontânea de janelas/pop-ups não solicitados durante o uso da internet são sintomas clássicos de infecção por vírus ou outros tipos de malware (gabarito C) — distinto de atualizações oficiais (não abrem pop-ups invasivos), arquivos compactados estáticos, falta de memória RAM isolada (não abre janelas) e programas oficiais em operação normal. RECORRÊNCIA: malware/códigos maliciosos é o ÚNICO eixo REAL com recorrência genuína neste corpus, confirmado por mais duas ocorrências independentes em Q707 e Q708 (provas distintas, sub-focos diferentes: antivírus/limitações e worm). Categoria: B) regra factual/conceitual. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (706, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Princípios da segurança da informação — CIA (origem=REAL)', 'ORIGEM: REAL (Fundatec, Per Crim (IGP RS)/IGP RS/Contabilidade e Economia, 2025). Fenômeno testado: julgamento de 3 assertivas sobre princípios de segurança — a proteção baseada em sigilo/controle de acesso define CONFIDENCIALIDADE (não autenticidade, que trata de identidade/autoria da fonte); a preservação do estado exato e original da informação, imune a alterações não autorizadas, define INTEGRIDADE (assertiva correta, gabarito B: apenas II); a garantia de acesso/operação sempre que solicitado por usuários autorizados define DISPONIBILIDADE (não conformidade). Distinção precisa entre CIA (Confidencialidade/Integridade/Disponibilidade) e os termos vizinhos Autenticidade e Conformidade, usados como distratores. Categoria: A) regra conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (707, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Malware — limitações do antivírus (origem=REAL)', 'ORIGEM: REAL (Fundatec, Per Crim (IGP RS)/IGP RS/Contabilidade e Economia, 2025 — mesma prova de Q706). Fenômeno testado: malwares são usados para fraudes/ataques/spam (correto); NÃO é sempre possível reverter ações ou recuperar dados vazados/perdidos — vazamento irreversível ou ransomware destrutivo (wiper) podem causar perda definitiva (correto identificar como falso o termo absoluto "sempre possível"); antivírus/antimalware ajudam a detectar, prevenir e remover códigos maliciosos, mas sem garantia de reversão total (gabarito C: 1ª e 3ª partes corretas, 2ª incorreta). CAUTELA: não ensinar que "antivírus sempre consegue recuperar tudo" — esta questão demonstra justamente o limite dessa ideia; termos absolutos ("sempre", "infalível", "100% seguro") são pista clássica de armadilha em provas de TI. RECORRÊNCIA: malware/códigos maliciosos é eixo RECORRENTE NESTE CORPUS (ver Q642 e Q708, provas independentes). Categoria: A) regra conceitual. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (708, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Worm (origem=REAL)', 'ORIGEM: REAL (Fundatec, Tec Per (IGP RS)/IGP RS/Técnico em Química, 2025). Fenômeno testado: código malicioso capaz de se replicar automaticamente por uma rede de computadores, enviando cópias de si mesmo sem necessidade de arquivo hospedeiro nem intervenção humana, explorando vulnerabilidades de protocolos/serviços, define WORM (gabarito E) — distinto de spam (envio em massa de mensagens), adware (exibição de propaganda), keylogger (captura de teclado) e spyware (termo genérico de espionagem). Contraste central: vírus precisa de hospedeiro e execução humana; worm é autônomo e se propaga sozinho pela rede. RECORRÊNCIA: malware/códigos maliciosos é eixo RECORRENTE NESTE CORPUS (ver Q642 e Q707, provas independentes). Categoria: B) regra factual/conceitual. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (709, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Backup (origem=REAL)', 'ORIGEM: REAL (Fundatec, Tec Per (IGP RS)/IGP RS/Técnico em Química, 2025 — mesma prova de Q708). Fenômeno testado: o processo de criar uma cópia de segurança de dados para permitir recuperação em caso de perda, dano, falha de hardware, ataque cibernético ou exclusão acidental é o BACKUP (gabarito C) — distinto de criptografia (codificação para confidencialidade), restore (etapa posterior de restauração a partir do backup), storage (equipamento de armazenamento físico) e antivírus (detecção/remoção de malware). Categoria: B) regra factual/conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta'),
    (710, 'a042af68-babf-4385-bcc4-2fa69e9b27cd'::uuid, 1, 'Hash e integridade forense (origem=REAL)', 'ORIGEM: REAL (Fundatec, Del Pol (PC RS)/PC RS, 2025). Fenômeno testado: o mecanismo técnico que garante a integridade de dados, permitindo verificar se um arquivo digital não sofreu alterações desde sua coleta até sua apresentação em juízo, é o HASH criptográfico (SHA-256, SHA-512, MD5) — função matemática unidirecional que converte dados em uma cadeia de comprimento fixo, usada em computação forense e cadeia de custódia (gabarito A), distinto de mixer/tumbler (anonimização de criptomoedas), log de auditoria (registro de eventos), chave simétrica (cifragem/decifragem, não resumo) e proxy (servidor intermediário). CAUTELA: tratar hash como função de resumo/impressão digital, não como "criptografia de mão única"; hash prova integridade, não garante sozinho autoria nem cifra o arquivo. Categoria: B) regra factual/conceitual. Incidência pontual neste corpus (1 prova independente) — não registrar como recorrente. Explicação armazenada NÃO alterada nesta curadoria.', 'alta')
)
select * from mapa order by questao_id, ordem_unidade;

-- ============================================================================
-- 2) LISTAS EXPLICITAS.
-- ============================================================================

-- 2a) Questoes classificadas (13/13).
-- 11,15,32,294,639,640,641,642,706,707,708,709,710

-- 2b) Questoes multiunidade: nenhuma

-- 2c) Questoes excluidas intencionalmente (fora de escopo/pendente de saneamento): nenhuma

-- ============================================================================
-- 3) Cobertura por unidade (questoes distintas). NAO forca nenhuma unidade
--    a atingir 10; unidades fracas sao GAP REAL DO BANCO, nao erro tecnico.
-- ============================================================================
-- U1 Segurança da informação: 13 questoes distintas
-- Total de vinculos esperados: 13 (13 questoes distintas
-- + 0 vinculo(s) extra(s) de multiunidade).
