-- Reversao segura, POS-APPLY, do lote AUTORAL DH-AUT-02 de Direitos
-- Humanos e Cidadania (33 questoes AUTORAL_PAPIRO / 165 alternativas /
-- 33 vinculos, cc77/cc78/cc79/cc80/cc81).
--
-- NAO EXECUTAR agora. Este arquivo so devera ser usado se, no futuro,
-- for necessario desfazer o apply ja confirmado (commit) de
-- supabase/importar_dh_aut_02.sql.
--
-- Mecanismo de identificacao: as 33 questoes sao localizadas
-- exclusivamente pelo texto EXATO do enunciado (a mesma chave usada nas
-- precondicoes do apply para garantir idempotencia). NAO usa DELETE
-- amplo por materia_id, assunto_id, banca ou origem — atinge
-- exclusivamente as 33 linhas cujo enunciado bate com um dos textos
-- abaixo, respeitando a ordem de FKs (vinculo -> alternativas -> questao).
--
-- Termina em COMMIT. So deve ser executado apos autorizacao humana
-- explicita, e apos novo teste_rollback proprio (nao incluido aqui,
-- pois este arquivo e de uso excepcional/pos-apply, nao parte do fluxo
-- normal de importacao).

begin;

set local request.jwt.claim.sub = 'e5523807-6cc8-4867-8a56-77c17552e56e';

create temporary table _dh_aut_02_enunciados (enunciado text) on commit drop;
insert into _dh_aut_02_enunciados (enunciado) values
('O Estado "Alfa", parte do Pacto Internacional sobre Direitos Econômicos, Sociais e Culturais (PIDESC), possui em sua legislação interna a garantia de um direito fundamental com espectro de proteção mais amplo do que o previsto no próprio Pacto. O governo de "Alfa", desejando reduzir custos, tenta restringir esse direito, argumentando que o PIDESC exige um grau menor de proteção. Considerando as disposições do PIDESC, essa atitude do Estado "Alfa" é:'),
('Conforme as disposições do Pacto Internacional sobre Direitos Econômicos, Sociais e Culturais (PIDESC), os Estados Partes reconhecem o direito de toda pessoa à:'),
('De acordo com o Pacto Internacional sobre Direitos Econômicos, Sociais e Culturais (PIDESC), no que tange aos direitos culturais, os Estados Partes reconhecem o direito de toda pessoa de beneficiar-se da proteção dos interesses morais e materiais decorrentes de toda produção científica, literária ou artística:'),
('Em relação ao direito ao trabalho reconhecido no Pacto Internacional sobre Direitos Econômicos, Sociais e Culturais (PIDESC), assinale a alternativa que apresenta uma das medidas expressamente previstas que os Estados Partes devem adotar para assegurar o pleno exercício desse direito.'),
('O Parlamento do Estado "Beta" aprovou uma lei que restringe determinados direitos econômicos reconhecidos no PIDESC. O propósito alegado na exposição de motivos da lei foi, exclusivamente, promover o bem-estar geral em uma sociedade democrática. As limitações impostas pela lei foram consideradas pelos tribunais locais como compatíveis com a natureza dos referidos direitos. Considerando a cláusula geral de limitações do PIDESC e a situação hipotética descrita, é correto afirmar que:'),
(E'Considere as seguintes assertivas sobre o Pacto Internacional sobre Direitos Econômicos, Sociais e Culturais (PIDESC):\n\nI. É proibida a restrição ou suspensão de direitos fundamentais vigentes em um Estado Parte, mediante leis ou convenções, sob o pretexto de que o PIDESC não os reconhece.\nII. Os Estados Partes reconhecem o direito de toda pessoa à previdência social, inclusive ao seguro social.\nIII. Os Estados Partes garantem proteção aos interesses materiais e morais resultantes de qualquer produção científica de que a pessoa detenha a propriedade, ainda que não seja a autora da obra.\n\nEstá correto o que se afirma em:'),
('O Pacto Internacional sobre Direitos Econômicos, Sociais e Culturais (PIDESC) estrutura diversos direitos fundamentais, entre os quais o direito ao trabalho e o direito à educação. Com base nas disposições do PIDESC, é correto afirmar que:'),
('O sistema normativo brasileiro incorpora os tratados de direitos humanos de forma diferenciada, a depender do quórum de aprovação parlamentar. Dentre os instrumentos internacionais que ostentam equivalência às emendas constitucionais no Brasil, encontra-se a:'),
('O Tratado de Marraqueche para Facilitar o Acesso a Obras Publicadas às Pessoas Cegas, com Deficiência Visual ou com outras Dificuldades para Ter Acesso ao Texto Impresso foi ratificado e promulgado pelo Estado brasileiro com uma característica formal relevante. De acordo com a sistemática constitucional brasileira, esse Tratado possui:'),
('No ordenamento jurídico brasileiro, a Convenção de Nova York sobre os Direitos das Pessoas com Deficiência possui posição hierárquica diferenciada. Assinale a alternativa que indica corretamente o instrumento normativo que, juntamente com a referida Convenção, foi aprovado sob a égide do artigo 5º, §3º, da Constituição Federal, ostentando equivalência de emenda constitucional.'),
('A jurisprudência do Supremo Tribunal Federal (STF) definiu o posicionamento hierárquico dos tratados internacionais de direitos humanos no ordenamento jurídico interno brasileiro. Considerando o entendimento firmado no julgamento do RE 466.343/SP, é correto afirmar que os tratados de direitos humanos incorporados ao Brasil antes da Emenda Constitucional nº 45/2004, ou aqueles que não foram aprovados com o quórum qualificado do art. 5º, §3º, da Constituição, possuem status normativo:'),
('O Brasil assinou recentemente um novo tratado internacional que cria diretrizes de proteção a grupos vulneráveis em tempos de crise. O Presidente da República encaminhou o texto ao Congresso Nacional, objetivando que o instrumento ganhe força normativa equivalente à das emendas constitucionais. Para que esse status jurídico seja alcançado, o Congresso Nacional deverá aprovar o tratado:'),
(E'No tocante ao status hierárquico dos tratados internacionais de direitos humanos no Brasil, julgue os itens a seguir, considerando a jurisprudência do Supremo Tribunal Federal e os ritos de aprovação congressual:\n\nI. O Tratado de Marraqueche e a Convenção Interamericana contra o Racismo ostentam status equivalente ao das emendas constitucionais.\nII. O Pacto Internacional dos Direitos Civis e Políticos (PIDCP) foi incorporado com equivalência de emenda constitucional, figurando no mesmo patamar do Protocolo Facultativo à Convenção sobre os Direitos das Pessoas com Deficiência.\nIII. A Convenção Americana sobre Direitos Humanos (Pacto de San José da Costa Rica) possui status supralegal, situando-se abaixo da Constituição Federal e acima das leis ordinárias.\n\nEstá correto o que se afirma em:'),
('Considerando o sistema constitucional brasileiro e a jurisprudência dominante do Supremo Tribunal Federal (STF) acerca da hierarquia dos tratados internacionais sobre direitos humanos, assinale a alternativa correta sobre as consequências formais de sua incorporação.'),
('Conforme o disposto no artigo 2º da Convenção Interamericana para Prevenir e Punir a Tortura, para os efeitos da referida Convenção, a definição de tortura inclui sofrimentos físicos ou mentais aplicados com fins de investigação, punição ou intimidação. No entanto, o mesmo dispositivo faz uma ressalva expressa em relação ao conceito de tortura quanto às penas ou sofrimentos inerentes a medidas legais. Sobre esse ponto, é correto afirmar que:'),
('Um policial militar recém-formado, cumprindo determinações expressas de seu Capitão durante um interrogatório, aplica severos castigos físicos em um suspeito detido para forçar uma confissão. Ao ser responsabilizado criminalmente, o policial argumenta que não poderia desobedecer à ordem hierárquica superior. À luz da Convenção Interamericana para Prevenir e Punir a Tortura, essa alegação de obediência hierárquica é:'),
('Durante uma rebelião em unidade prisional, o diretor do presídio, um funcionário público, presencia agentes penitenciários agredindo fisicamente os detentos com o objetivo deliberado de aplicar castigo pessoal. Embora tivesse plena capacidade operacional e autoridade para interromper imediatamente a violência, o diretor decide cruzar os braços e assistir passivamente, sem impedir os atos. Com base na Convenção Interamericana para Prevenir e Punir a Tortura (art. 3º), a conduta do diretor:'),
('Agentes estatais, durante interrogatórios prolongados de um suspeito de espionagem, não utilizaram agressões físicas, choques ou qualquer método que causasse dor física ou angústia psicológica severa imediata. Em vez disso, aplicaram drogas experimentais e técnicas de privação sensorial que anularam a personalidade da vítima e diminuíram significativamente sua capacidade mental consciente, com o fim de obter informações. À luz da Convenção Interamericana para Prevenir e Punir a Tortura, a conduta desses agentes:'),
('O comandante de uma instalação prisional em um país signatário da Convenção Interamericana para Prevenir e Punir a Tortura determinou o uso de tortura contra um grupo de detentos altamente perigosos, líderes de uma facção criminosa. Após investigação, o comandante justificou seus atos formalmente, alegando a extrema periculosidade dos detidos e a grave insegurança do estabelecimento penitenciário, que ameaçava a vida dos próprios guardas. Com base na referida Convenção, a justificativa do comandante é:'),
('Os Estados Partes da Convenção Interamericana para Prevenir e Punir a Tortura assumem diversas obrigações de natureza legislativa perante o sistema interamericano. Assinale a alternativa que descreve corretamente o dever assumido pelos Estados quanto ao tratamento do ato de tortura em seu ordenamento jurídico penal.'),
(E'Com relação à responsabilização penal e às justificativas para a tortura na Convenção Interamericana, analise as assertivas abaixo:\n\nI. São responsabilizados pelo delito de tortura os empregados públicos que, podendo impedi-la, não o façam.\nII. O fato de o agente público ter agido sob ordens de um superior exime-o da responsabilidade penal, respondendo unicamente o superior hierárquico.\nIII. A suspensão de garantias constitucionais por estado de emergência não pode ser invocada como justificativa para a tortura.\n\nEstá correto o que se afirma em:'),
('Durante o cumprimento de um mandado de prisão preventiva por crimes financeiros em desfavor de um empresário idoso, a equipe policial encontrou-o em sua residência. O alvo colaborou prontamente com os agentes, não apresentou qualquer resistência, não demonstrou sinais de fuga e não impôs qualquer risco ou perigo à integridade física própria ou alheia. Ainda assim, por determinação do delegado, ele foi algemado. À luz do entendimento sumulado do Supremo Tribunal Federal (Súmula Vinculante 11), o uso de algemas nesta situação foi:'),
('Agentes de segurança pública realizam a captura de um suspeito em flagrante delito por roubo à mão armada. O suspeito oferece violenta resistência e tenta se desvencilhar dos policiais, havendo evidente perigo à integridade física da própria guarnição e de transeuntes no local. Os agentes conseguem dominá-lo e aplicam as algemas para realizar o transporte seguro, formalizando posteriormente, por escrito, a excepcionalidade do uso. Considerando o teor da Súmula Vinculante 11, a conduta dos policiais:'),
('Policiais em patrulhamento noturno sentem forte odor de entorpecentes vindos de uma residência. Pela fresta do muro baixo, observam nitidamente um indivíduo embalando grande quantidade de drogas sobre uma mesa. Diante da situação de flagrante delito em curso, os policiais ingressam forçadamente no domicílio, sem mandado judicial, e efetuam a prisão. Posteriormente, a equipe justifica o ingresso no domicílio com base nos elementos visuais que possuíam antes da entrada. À luz do Tema 280 da repercussão geral do STF, a ação policial foi:'),
('A polícia recebe uma ligação anônima informando genericamente que "na casa da esquina há pessoas traficando drogas". Sem realizar nenhuma diligência prévia, monitoramento ou constatar visualmente qualquer movimentação atípica que indicasse crime, a guarnição chega ao local, arromba a porta da residência e, por acaso, encontra pequena quantidade de drogas, prendendo o morador em flagrante. Analisando o caso sob a ótica da jurisprudência do STF (Tema 280), o ingresso no domicílio e as provas dele decorrentes são:'),
('A Constituição Federal consagra que "a casa é asilo inviolável do indivíduo, ninguém nela podendo penetrar sem consentimento do morador, salvo em caso de flagrante delito ou desastre, ou para prestar socorro, ou, durante o dia, por determinação judicial" (art. 5º, XI). Ao densificar e interpretar esse comando, o Supremo Tribunal Federal firmou tese vinculante (Tema 280 da repercussão geral) estipulando um requisito normativo não escrito expressamente no dispositivo constitucional, a ser observado pelas forças policiais para validar o ingresso por flagrante delito sem mandado. Esse requisito jurisprudencial adicional consiste na exigência de:'),
('O descumprimento das regras relativas à excepcionalidade do uso de algemas acarreta severas consequências legais para o agente público e para a validade do ato. Assinale a alternativa que elenca adequadamente as consequências previstas na Súmula Vinculante 11 do STF para o uso indevido de algemas.'),
('Os precedentes e as súmulas do Supremo Tribunal Federal balizam a atuação das forças de segurança pública, impondo balizas para garantir o respeito aos direitos fundamentais. A respeito de dois entendimentos centrais da jurisprudência, assinale a alternativa que associa corretamente a tese fixada ao seu respectivo instituto garantidor.'),
('Um Estado soberano decide punir oponentes políticos com a aplicação de castigos corporais que configuram tortura, fundamentando a prática em antigas tradições religiosas e no contexto cultural exclusivo de seu povo. Em fóruns internacionais, as autoridades daquele país invocam a defesa da soberania e afirmam que valores ocidentais não podem ser impostos a outras culturas. À luz do Direito Internacional dos Direitos Humanos e do paradigma estabelecido na Conferência de Viena de 1993, essa alegação de ordem cultural é juridicamente:'),
('O governo de um determinado Estado decide suprimir severamente o repasse de verbas destinadas à educação básica pública, inviabilizando a alfabetização de parcela significativa de sua população mais vulnerável. Paralelamente, como reflexo da falta de instrução formal mínima, esses mesmos cidadãos não conseguem se registrar para votar e enfrentam extrema dificuldade para organizar petições contra as ações governamentais, sendo impedidos de participar do debate público (direito político). O fenômeno em que a violação de um direito econômico e social impacta diretamente o exercício de um direito civil ou político exemplifica a característica de direitos humanos denominada:'),
('Com o objetivo de combater uma escalada nos índices de criminalidade, o governo e a cúpula da segurança pública estudam aprovar uma medida de segurança que autoriza a marcação permanente da pele, por meio de ferros aquecidos, de indivíduos condenados em segunda instância por roubo qualificado, visando à fácil identificação social desses agentes. Sob a ótica do Direito Constitucional e dos Direitos Humanos, tal medida proposta é:'),
('O recrudescimento da violência contra a própria vida entre profissionais de segurança pública motivou a edição da Lei nº 14.531/2023, que incluiu novos dispositivos na Lei nº 13.675/2018 (Sistema Único de Segurança Pública - SUSP). Segundo o art. 42-A, § 2º, a prevenção da violência autoprovocada e do suicídio dos profissionais da segurança deverá observar, entre outras, as seguintes diretrizes:'),
('Além de focar na saúde mental, a Lei nº 13.675/2018 (SUSP), alterada pela Lei nº 14.531/2023, estabelece parâmetros cruciais relativos à proteção integral dos profissionais do sistema de segurança pública. Nos termos do art. 42-B, assinale a alternativa que contém diretrizes de promoção da proteção física e capacitação que devem ser seguidas pelas instituições.');

do $$
declare
  v_cnt int;
begin
  select count(*) into v_cnt from public.questoes where enunciado in (select enunciado from _dh_aut_02_enunciados);
  if v_cnt <> 33 then
    raise exception 'Abortado: % questao(oes) encontrada(s) pelo criterio de enunciado exato (esperado exatamente 33) — nao reverter as cegas', v_cnt;
  end if;
end $$;

delete from public.questao_unidades_pedagogicas
where questao_id in (select id from public.questoes where enunciado in (select enunciado from _dh_aut_02_enunciados));

delete from public.alternativas
where questao_id in (select id from public.questoes where enunciado in (select enunciado from _dh_aut_02_enunciados));

delete from public.questoes
where enunciado in (select enunciado from _dh_aut_02_enunciados);

commit;
